// Code generated by ent, DO NOT EDIT.

package steerrequest

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/francogalfre/coop/apps/relay/internal/db/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.SteerRequest {
	return predicate.SteerRequest(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.SteerRequest {
	return predicate.SteerRequest(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.SteerRequest {
	return predicate.SteerRequest(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.SteerRequest {
	return predicate.SteerRequest(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.SteerRequest {
	return predicate.SteerRequest(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.SteerRequest {
	return predicate.SteerRequest(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.SteerRequest {
	return predicate.SteerRequest(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.SteerRequest {
	return predicate.SteerRequest(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.SteerRequest {
	return predicate.SteerRequest(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.SteerRequest {
	return predicate.SteerRequest(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.SteerRequest {
	return predicate.SteerRequest(sql.FieldContainsFold(FieldID, id))
}

// ActorID applies equality check predicate on the "actor_id" field. It's identical to ActorIDEQ.
func ActorID(v string) predicate.SteerRequest {
	return predicate.SteerRequest(sql.FieldEQ(FieldActorID, v))
}

// ActorDisplayName applies equality check predicate on the "actor_display_name" field. It's identical to ActorDisplayNameEQ.
func ActorDisplayName(v string) predicate.SteerRequest {
	return predicate.SteerRequest(sql.FieldEQ(FieldActorDisplayName, v))
}

// ActorAvatarURL applies equality check predicate on the "actor_avatar_url" field. It's identical to ActorAvatarURLEQ.
func ActorAvatarURL(v string) predicate.SteerRequest {
	return predicate.SteerRequest(sql.FieldEQ(FieldActorAvatarURL, v))
}

// Text applies equality check predicate on the "text" field. It's identical to TextEQ.
func Text(v string) predicate.SteerRequest {
	return predicate.SteerRequest(sql.FieldEQ(FieldText, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SteerRequest {
	return predicate.SteerRequest(sql.FieldEQ(FieldCreatedAt, v))
}

// ActorIDEQ applies the EQ predicate on the "actor_id" field.
func ActorIDEQ(v string) predicate.SteerRequest {
	return predicate.SteerRequest(sql.FieldEQ(FieldActorID, v))
}

// ActorIDNEQ applies the NEQ predicate on the "actor_id" field.
func ActorIDNEQ(v string) predicate.SteerRequest {
	return predicate.SteerRequest(sql.FieldNEQ(FieldActorID, v))
}

// ActorIDIn applies the In predicate on the "actor_id" field.
func ActorIDIn(vs ...string) predicate.SteerRequest {
	return predicate.SteerRequest(sql.FieldIn(FieldActorID, vs...))
}

// ActorIDNotIn applies the NotIn predicate on the "actor_id" field.
func ActorIDNotIn(vs ...string) predicate.SteerRequest {
	return predicate.SteerRequest(sql.FieldNotIn(FieldActorID, vs...))
}

// ActorIDGT applies the GT predicate on the "actor_id" field.
func ActorIDGT(v string) predicate.SteerRequest {
	return predicate.SteerRequest(sql.FieldGT(FieldActorID, v))
}

// ActorIDGTE applies the GTE predicate on the "actor_id" field.
func ActorIDGTE(v string) predicate.SteerRequest {
	return predicate.SteerRequest(sql.FieldGTE(FieldActorID, v))
}

// ActorIDLT applies the LT predicate on the "actor_id" field.
func ActorIDLT(v string) predicate.SteerRequest {
	return predicate.SteerRequest(sql.FieldLT(FieldActorID, v))
}

// ActorIDLTE applies the LTE predicate on the "actor_id" field.
func ActorIDLTE(v string) predicate.SteerRequest {
	return predicate.SteerRequest(sql.FieldLTE(FieldActorID, v))
}

// ActorIDContains applies the Contains predicate on the "actor_id" field.
func ActorIDContains(v string) predicate.SteerRequest {
	return predicate.SteerRequest(sql.FieldContains(FieldActorID, v))
}

// ActorIDHasPrefix applies the HasPrefix predicate on the "actor_id" field.
func ActorIDHasPrefix(v string) predicate.SteerRequest {
	return predicate.SteerRequest(sql.FieldHasPrefix(FieldActorID, v))
}

// ActorIDHasSuffix applies the HasSuffix predicate on the "actor_id" field.
func ActorIDHasSuffix(v string) predicate.SteerRequest {
	return predicate.SteerRequest(sql.FieldHasSuffix(FieldActorID, v))
}

// ActorIDEqualFold applies the EqualFold predicate on the "actor_id" field.
func ActorIDEqualFold(v string) predicate.SteerRequest {
	return predicate.SteerRequest(sql.FieldEqualFold(FieldActorID, v))
}

// ActorIDContainsFold applies the ContainsFold predicate on the "actor_id" field.
func ActorIDContainsFold(v string) predicate.SteerRequest {
	return predicate.SteerRequest(sql.FieldContainsFold(FieldActorID, v))
}

// ActorDisplayNameEQ applies the EQ predicate on the "actor_display_name" field.
func ActorDisplayNameEQ(v string) predicate.SteerRequest {
	return predicate.SteerRequest(sql.FieldEQ(FieldActorDisplayName, v))
}

// ActorDisplayNameNEQ applies the NEQ predicate on the "actor_display_name" field.
func ActorDisplayNameNEQ(v string) predicate.SteerRequest {
	return predicate.SteerRequest(sql.FieldNEQ(FieldActorDisplayName, v))
}

// ActorDisplayNameIn applies the In predicate on the "actor_display_name" field.
func ActorDisplayNameIn(vs ...string) predicate.SteerRequest {
	return predicate.SteerRequest(sql.FieldIn(FieldActorDisplayName, vs...))
}

// ActorDisplayNameNotIn applies the NotIn predicate on the "actor_display_name" field.
func ActorDisplayNameNotIn(vs ...string) predicate.SteerRequest {
	return predicate.SteerRequest(sql.FieldNotIn(FieldActorDisplayName, vs...))
}

// ActorDisplayNameGT applies the GT predicate on the "actor_display_name" field.
func ActorDisplayNameGT(v string) predicate.SteerRequest {
	return predicate.SteerRequest(sql.FieldGT(FieldActorDisplayName, v))
}

// ActorDisplayNameGTE applies the GTE predicate on the "actor_display_name" field.
func ActorDisplayNameGTE(v string) predicate.SteerRequest {
	return predicate.SteerRequest(sql.FieldGTE(FieldActorDisplayName, v))
}

// ActorDisplayNameLT applies the LT predicate on the "actor_display_name" field.
func ActorDisplayNameLT(v string) predicate.SteerRequest {
	return predicate.SteerRequest(sql.FieldLT(FieldActorDisplayName, v))
}

// ActorDisplayNameLTE applies the LTE predicate on the "actor_display_name" field.
func ActorDisplayNameLTE(v string) predicate.SteerRequest {
	return predicate.SteerRequest(sql.FieldLTE(FieldActorDisplayName, v))
}

// ActorDisplayNameContains applies the Contains predicate on the "actor_display_name" field.
func ActorDisplayNameContains(v string) predicate.SteerRequest {
	return predicate.SteerRequest(sql.FieldContains(FieldActorDisplayName, v))
}

// ActorDisplayNameHasPrefix applies the HasPrefix predicate on the "actor_display_name" field.
func ActorDisplayNameHasPrefix(v string) predicate.SteerRequest {
	return predicate.SteerRequest(sql.FieldHasPrefix(FieldActorDisplayName, v))
}

// ActorDisplayNameHasSuffix applies the HasSuffix predicate on the "actor_display_name" field.
func ActorDisplayNameHasSuffix(v string) predicate.SteerRequest {
	return predicate.SteerRequest(sql.FieldHasSuffix(FieldActorDisplayName, v))
}

// ActorDisplayNameEqualFold applies the EqualFold predicate on the "actor_display_name" field.
func ActorDisplayNameEqualFold(v string) predicate.SteerRequest {
	return predicate.SteerRequest(sql.FieldEqualFold(FieldActorDisplayName, v))
}

// ActorDisplayNameContainsFold applies the ContainsFold predicate on the "actor_display_name" field.
func ActorDisplayNameContainsFold(v string) predicate.SteerRequest {
	return predicate.SteerRequest(sql.FieldContainsFold(FieldActorDisplayName, v))
}

// ActorAvatarURLEQ applies the EQ predicate on the "actor_avatar_url" field.
func ActorAvatarURLEQ(v string) predicate.SteerRequest {
	return predicate.SteerRequest(sql.FieldEQ(FieldActorAvatarURL, v))
}

// ActorAvatarURLNEQ applies the NEQ predicate on the "actor_avatar_url" field.
func ActorAvatarURLNEQ(v string) predicate.SteerRequest {
	return predicate.SteerRequest(sql.FieldNEQ(FieldActorAvatarURL, v))
}

// ActorAvatarURLIn applies the In predicate on the "actor_avatar_url" field.
func ActorAvatarURLIn(vs ...string) predicate.SteerRequest {
	return predicate.SteerRequest(sql.FieldIn(FieldActorAvatarURL, vs...))
}

// ActorAvatarURLNotIn applies the NotIn predicate on the "actor_avatar_url" field.
func ActorAvatarURLNotIn(vs ...string) predicate.SteerRequest {
	return predicate.SteerRequest(sql.FieldNotIn(FieldActorAvatarURL, vs...))
}

// ActorAvatarURLGT applies the GT predicate on the "actor_avatar_url" field.
func ActorAvatarURLGT(v string) predicate.SteerRequest {
	return predicate.SteerRequest(sql.FieldGT(FieldActorAvatarURL, v))
}

// ActorAvatarURLGTE applies the GTE predicate on the "actor_avatar_url" field.
func ActorAvatarURLGTE(v string) predicate.SteerRequest {
	return predicate.SteerRequest(sql.FieldGTE(FieldActorAvatarURL, v))
}

// ActorAvatarURLLT applies the LT predicate on the "actor_avatar_url" field.
func ActorAvatarURLLT(v string) predicate.SteerRequest {
	return predicate.SteerRequest(sql.FieldLT(FieldActorAvatarURL, v))
}

// ActorAvatarURLLTE applies the LTE predicate on the "actor_avatar_url" field.
func ActorAvatarURLLTE(v string) predicate.SteerRequest {
	return predicate.SteerRequest(sql.FieldLTE(FieldActorAvatarURL, v))
}

// ActorAvatarURLContains applies the Contains predicate on the "actor_avatar_url" field.
func ActorAvatarURLContains(v string) predicate.SteerRequest {
	return predicate.SteerRequest(sql.FieldContains(FieldActorAvatarURL, v))
}

// ActorAvatarURLHasPrefix applies the HasPrefix predicate on the "actor_avatar_url" field.
func ActorAvatarURLHasPrefix(v string) predicate.SteerRequest {
	return predicate.SteerRequest(sql.FieldHasPrefix(FieldActorAvatarURL, v))
}

// ActorAvatarURLHasSuffix applies the HasSuffix predicate on the "actor_avatar_url" field.
func ActorAvatarURLHasSuffix(v string) predicate.SteerRequest {
	return predicate.SteerRequest(sql.FieldHasSuffix(FieldActorAvatarURL, v))
}

// ActorAvatarURLEqualFold applies the EqualFold predicate on the "actor_avatar_url" field.
func ActorAvatarURLEqualFold(v string) predicate.SteerRequest {
	return predicate.SteerRequest(sql.FieldEqualFold(FieldActorAvatarURL, v))
}

// ActorAvatarURLContainsFold applies the ContainsFold predicate on the "actor_avatar_url" field.
func ActorAvatarURLContainsFold(v string) predicate.SteerRequest {
	return predicate.SteerRequest(sql.FieldContainsFold(FieldActorAvatarURL, v))
}

// TextEQ applies the EQ predicate on the "text" field.
func TextEQ(v string) predicate.SteerRequest {
	return predicate.SteerRequest(sql.FieldEQ(FieldText, v))
}

// TextNEQ applies the NEQ predicate on the "text" field.
func TextNEQ(v string) predicate.SteerRequest {
	return predicate.SteerRequest(sql.FieldNEQ(FieldText, v))
}

// TextIn applies the In predicate on the "text" field.
func TextIn(vs ...string) predicate.SteerRequest {
	return predicate.SteerRequest(sql.FieldIn(FieldText, vs...))
}

// TextNotIn applies the NotIn predicate on the "text" field.
func TextNotIn(vs ...string) predicate.SteerRequest {
	return predicate.SteerRequest(sql.FieldNotIn(FieldText, vs...))
}

// TextGT applies the GT predicate on the "text" field.
func TextGT(v string) predicate.SteerRequest {
	return predicate.SteerRequest(sql.FieldGT(FieldText, v))
}

// TextGTE applies the GTE predicate on the "text" field.
func TextGTE(v string) predicate.SteerRequest {
	return predicate.SteerRequest(sql.FieldGTE(FieldText, v))
}

// TextLT applies the LT predicate on the "text" field.
func TextLT(v string) predicate.SteerRequest {
	return predicate.SteerRequest(sql.FieldLT(FieldText, v))
}

// TextLTE applies the LTE predicate on the "text" field.
func TextLTE(v string) predicate.SteerRequest {
	return predicate.SteerRequest(sql.FieldLTE(FieldText, v))
}

// TextContains applies the Contains predicate on the "text" field.
func TextContains(v string) predicate.SteerRequest {
	return predicate.SteerRequest(sql.FieldContains(FieldText, v))
}

// TextHasPrefix applies the HasPrefix predicate on the "text" field.
func TextHasPrefix(v string) predicate.SteerRequest {
	return predicate.SteerRequest(sql.FieldHasPrefix(FieldText, v))
}

// TextHasSuffix applies the HasSuffix predicate on the "text" field.
func TextHasSuffix(v string) predicate.SteerRequest {
	return predicate.SteerRequest(sql.FieldHasSuffix(FieldText, v))
}

// TextEqualFold applies the EqualFold predicate on the "text" field.
func TextEqualFold(v string) predicate.SteerRequest {
	return predicate.SteerRequest(sql.FieldEqualFold(FieldText, v))
}

// TextContainsFold applies the ContainsFold predicate on the "text" field.
func TextContainsFold(v string) predicate.SteerRequest {
	return predicate.SteerRequest(sql.FieldContainsFold(FieldText, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SteerRequest {
	return predicate.SteerRequest(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SteerRequest {
	return predicate.SteerRequest(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SteerRequest {
	return predicate.SteerRequest(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SteerRequest {
	return predicate.SteerRequest(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SteerRequest {
	return predicate.SteerRequest(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SteerRequest {
	return predicate.SteerRequest(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SteerRequest {
	return predicate.SteerRequest(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SteerRequest {
	return predicate.SteerRequest(sql.FieldLTE(FieldCreatedAt, v))
}

// HasSession applies the HasEdge predicate on the "session" edge.
func HasSession() predicate.SteerRequest {
	return predicate.SteerRequest(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SessionTable, SessionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSessionWith applies the HasEdge predicate on the "session" edge with a given conditions (other predicates).
func HasSessionWith(preds ...predicate.AgentSession) predicate.SteerRequest {
	return predicate.SteerRequest(func(s *sql.Selector) {
		step := newSessionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SteerRequest) predicate.SteerRequest {
	return predicate.SteerRequest(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SteerRequest) predicate.SteerRequest {
	return predicate.SteerRequest(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SteerRequest) predicate.SteerRequest {
	return predicate.SteerRequest(sql.NotPredicates(p))
}
