// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/francogalfre/coop/apps/relay/internal/db/ent/agentsession"
	"github.com/francogalfre/coop/apps/relay/internal/db/ent/event"
	"github.com/francogalfre/coop/apps/relay/internal/db/ent/predicate"
	"github.com/francogalfre/coop/apps/relay/internal/db/ent/project"
)

// AgentSessionUpdate is the builder for updating AgentSession entities.
type AgentSessionUpdate struct {
	config
	hooks    []Hook
	mutation *AgentSessionMutation
}

// Where appends a list predicates to the AgentSessionUpdate builder.
func (_u *AgentSessionUpdate) Where(ps ...predicate.AgentSession) *AgentSessionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOwnerID sets the "owner_id" field.
func (_u *AgentSessionUpdate) SetOwnerID(v string) *AgentSessionUpdate {
	_u.mutation.SetOwnerID(v)
	return _u
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (_u *AgentSessionUpdate) SetNillableOwnerID(v *string) *AgentSessionUpdate {
	if v != nil {
		_u.SetOwnerID(*v)
	}
	return _u
}

// SetRepo sets the "repo" field.
func (_u *AgentSessionUpdate) SetRepo(v string) *AgentSessionUpdate {
	_u.mutation.SetRepo(v)
	return _u
}

// SetNillableRepo sets the "repo" field if the given value is not nil.
func (_u *AgentSessionUpdate) SetNillableRepo(v *string) *AgentSessionUpdate {
	if v != nil {
		_u.SetRepo(*v)
	}
	return _u
}

// SetCwd sets the "cwd" field.
func (_u *AgentSessionUpdate) SetCwd(v string) *AgentSessionUpdate {
	_u.mutation.SetCwd(v)
	return _u
}

// SetNillableCwd sets the "cwd" field if the given value is not nil.
func (_u *AgentSessionUpdate) SetNillableCwd(v *string) *AgentSessionUpdate {
	if v != nil {
		_u.SetCwd(*v)
	}
	return _u
}

// SetHarness sets the "harness" field.
func (_u *AgentSessionUpdate) SetHarness(v string) *AgentSessionUpdate {
	_u.mutation.SetHarness(v)
	return _u
}

// SetNillableHarness sets the "harness" field if the given value is not nil.
func (_u *AgentSessionUpdate) SetNillableHarness(v *string) *AgentSessionUpdate {
	if v != nil {
		_u.SetHarness(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *AgentSessionUpdate) SetStatus(v string) *AgentSessionUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AgentSessionUpdate) SetNillableStatus(v *string) *AgentSessionUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetMode sets the "mode" field.
func (_u *AgentSessionUpdate) SetMode(v string) *AgentSessionUpdate {
	_u.mutation.SetMode(v)
	return _u
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (_u *AgentSessionUpdate) SetNillableMode(v *string) *AgentSessionUpdate {
	if v != nil {
		_u.SetMode(*v)
	}
	return _u
}

// SetNextSeq sets the "next_seq" field.
func (_u *AgentSessionUpdate) SetNextSeq(v int) *AgentSessionUpdate {
	_u.mutation.ResetNextSeq()
	_u.mutation.SetNextSeq(v)
	return _u
}

// SetNillableNextSeq sets the "next_seq" field if the given value is not nil.
func (_u *AgentSessionUpdate) SetNillableNextSeq(v *int) *AgentSessionUpdate {
	if v != nil {
		_u.SetNextSeq(*v)
	}
	return _u
}

// AddNextSeq adds value to the "next_seq" field.
func (_u *AgentSessionUpdate) AddNextSeq(v int) *AgentSessionUpdate {
	_u.mutation.AddNextSeq(v)
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *AgentSessionUpdate) SetStartedAt(v time.Time) *AgentSessionUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *AgentSessionUpdate) SetNillableStartedAt(v *time.Time) *AgentSessionUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// SetEndedAt sets the "ended_at" field.
func (_u *AgentSessionUpdate) SetEndedAt(v time.Time) *AgentSessionUpdate {
	_u.mutation.SetEndedAt(v)
	return _u
}

// SetNillableEndedAt sets the "ended_at" field if the given value is not nil.
func (_u *AgentSessionUpdate) SetNillableEndedAt(v *time.Time) *AgentSessionUpdate {
	if v != nil {
		_u.SetEndedAt(*v)
	}
	return _u
}

// ClearEndedAt clears the value of the "ended_at" field.
func (_u *AgentSessionUpdate) ClearEndedAt() *AgentSessionUpdate {
	_u.mutation.ClearEndedAt()
	return _u
}

// SetProjectID sets the "project" edge to the Project entity by ID.
func (_u *AgentSessionUpdate) SetProjectID(id int) *AgentSessionUpdate {
	_u.mutation.SetProjectID(id)
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *AgentSessionUpdate) SetProject(v *Project) *AgentSessionUpdate {
	return _u.SetProjectID(v.ID)
}

// AddEventIDs adds the "events" edge to the Event entity by IDs.
func (_u *AgentSessionUpdate) AddEventIDs(ids ...int) *AgentSessionUpdate {
	_u.mutation.AddEventIDs(ids...)
	return _u
}

// AddEvents adds the "events" edges to the Event entity.
func (_u *AgentSessionUpdate) AddEvents(v ...*Event) *AgentSessionUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEventIDs(ids...)
}

// Mutation returns the AgentSessionMutation object of the builder.
func (_u *AgentSessionUpdate) Mutation() *AgentSessionMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *AgentSessionUpdate) ClearProject() *AgentSessionUpdate {
	_u.mutation.ClearProject()
	return _u
}

// ClearEvents clears all "events" edges to the Event entity.
func (_u *AgentSessionUpdate) ClearEvents() *AgentSessionUpdate {
	_u.mutation.ClearEvents()
	return _u
}

// RemoveEventIDs removes the "events" edge to Event entities by IDs.
func (_u *AgentSessionUpdate) RemoveEventIDs(ids ...int) *AgentSessionUpdate {
	_u.mutation.RemoveEventIDs(ids...)
	return _u
}

// RemoveEvents removes "events" edges to Event entities.
func (_u *AgentSessionUpdate) RemoveEvents(v ...*Event) *AgentSessionUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEventIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AgentSessionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AgentSessionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AgentSessionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AgentSessionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AgentSessionUpdate) check() error {
	if v, ok := _u.mutation.OwnerID(); ok {
		if err := agentsession.OwnerIDValidator(v); err != nil {
			return &ValidationError{Name: "owner_id", err: fmt.Errorf(`ent: validator failed for field "AgentSession.owner_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NextSeq(); ok {
		if err := agentsession.NextSeqValidator(v); err != nil {
			return &ValidationError{Name: "next_seq", err: fmt.Errorf(`ent: validator failed for field "AgentSession.next_seq": %w`, err)}
		}
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AgentSession.project"`)
	}
	return nil
}

func (_u *AgentSessionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(agentsession.Table, agentsession.Columns, sqlgraph.NewFieldSpec(agentsession.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OwnerID(); ok {
		_spec.SetField(agentsession.FieldOwnerID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Repo(); ok {
		_spec.SetField(agentsession.FieldRepo, field.TypeString, value)
	}
	if value, ok := _u.mutation.Cwd(); ok {
		_spec.SetField(agentsession.FieldCwd, field.TypeString, value)
	}
	if value, ok := _u.mutation.Harness(); ok {
		_spec.SetField(agentsession.FieldHarness, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(agentsession.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Mode(); ok {
		_spec.SetField(agentsession.FieldMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.NextSeq(); ok {
		_spec.SetField(agentsession.FieldNextSeq, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedNextSeq(); ok {
		_spec.AddField(agentsession.FieldNextSeq, field.TypeInt, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(agentsession.FieldStartedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndedAt(); ok {
		_spec.SetField(agentsession.FieldEndedAt, field.TypeTime, value)
	}
	if _u.mutation.EndedAtCleared() {
		_spec.ClearField(agentsession.FieldEndedAt, field.TypeTime)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentsession.ProjectTable,
			Columns: []string{agentsession.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentsession.ProjectTable,
			Columns: []string{agentsession.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agentsession.EventsTable,
			Columns: []string{agentsession.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEventsIDs(); len(nodes) > 0 && !_u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agentsession.EventsTable,
			Columns: []string{agentsession.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agentsession.EventsTable,
			Columns: []string{agentsession.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agentsession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AgentSessionUpdateOne is the builder for updating a single AgentSession entity.
type AgentSessionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AgentSessionMutation
}

// SetOwnerID sets the "owner_id" field.
func (_u *AgentSessionUpdateOne) SetOwnerID(v string) *AgentSessionUpdateOne {
	_u.mutation.SetOwnerID(v)
	return _u
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (_u *AgentSessionUpdateOne) SetNillableOwnerID(v *string) *AgentSessionUpdateOne {
	if v != nil {
		_u.SetOwnerID(*v)
	}
	return _u
}

// SetRepo sets the "repo" field.
func (_u *AgentSessionUpdateOne) SetRepo(v string) *AgentSessionUpdateOne {
	_u.mutation.SetRepo(v)
	return _u
}

// SetNillableRepo sets the "repo" field if the given value is not nil.
func (_u *AgentSessionUpdateOne) SetNillableRepo(v *string) *AgentSessionUpdateOne {
	if v != nil {
		_u.SetRepo(*v)
	}
	return _u
}

// SetCwd sets the "cwd" field.
func (_u *AgentSessionUpdateOne) SetCwd(v string) *AgentSessionUpdateOne {
	_u.mutation.SetCwd(v)
	return _u
}

// SetNillableCwd sets the "cwd" field if the given value is not nil.
func (_u *AgentSessionUpdateOne) SetNillableCwd(v *string) *AgentSessionUpdateOne {
	if v != nil {
		_u.SetCwd(*v)
	}
	return _u
}

// SetHarness sets the "harness" field.
func (_u *AgentSessionUpdateOne) SetHarness(v string) *AgentSessionUpdateOne {
	_u.mutation.SetHarness(v)
	return _u
}

// SetNillableHarness sets the "harness" field if the given value is not nil.
func (_u *AgentSessionUpdateOne) SetNillableHarness(v *string) *AgentSessionUpdateOne {
	if v != nil {
		_u.SetHarness(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *AgentSessionUpdateOne) SetStatus(v string) *AgentSessionUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AgentSessionUpdateOne) SetNillableStatus(v *string) *AgentSessionUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetMode sets the "mode" field.
func (_u *AgentSessionUpdateOne) SetMode(v string) *AgentSessionUpdateOne {
	_u.mutation.SetMode(v)
	return _u
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (_u *AgentSessionUpdateOne) SetNillableMode(v *string) *AgentSessionUpdateOne {
	if v != nil {
		_u.SetMode(*v)
	}
	return _u
}

// SetNextSeq sets the "next_seq" field.
func (_u *AgentSessionUpdateOne) SetNextSeq(v int) *AgentSessionUpdateOne {
	_u.mutation.ResetNextSeq()
	_u.mutation.SetNextSeq(v)
	return _u
}

// SetNillableNextSeq sets the "next_seq" field if the given value is not nil.
func (_u *AgentSessionUpdateOne) SetNillableNextSeq(v *int) *AgentSessionUpdateOne {
	if v != nil {
		_u.SetNextSeq(*v)
	}
	return _u
}

// AddNextSeq adds value to the "next_seq" field.
func (_u *AgentSessionUpdateOne) AddNextSeq(v int) *AgentSessionUpdateOne {
	_u.mutation.AddNextSeq(v)
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *AgentSessionUpdateOne) SetStartedAt(v time.Time) *AgentSessionUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *AgentSessionUpdateOne) SetNillableStartedAt(v *time.Time) *AgentSessionUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// SetEndedAt sets the "ended_at" field.
func (_u *AgentSessionUpdateOne) SetEndedAt(v time.Time) *AgentSessionUpdateOne {
	_u.mutation.SetEndedAt(v)
	return _u
}

// SetNillableEndedAt sets the "ended_at" field if the given value is not nil.
func (_u *AgentSessionUpdateOne) SetNillableEndedAt(v *time.Time) *AgentSessionUpdateOne {
	if v != nil {
		_u.SetEndedAt(*v)
	}
	return _u
}

// ClearEndedAt clears the value of the "ended_at" field.
func (_u *AgentSessionUpdateOne) ClearEndedAt() *AgentSessionUpdateOne {
	_u.mutation.ClearEndedAt()
	return _u
}

// SetProjectID sets the "project" edge to the Project entity by ID.
func (_u *AgentSessionUpdateOne) SetProjectID(id int) *AgentSessionUpdateOne {
	_u.mutation.SetProjectID(id)
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *AgentSessionUpdateOne) SetProject(v *Project) *AgentSessionUpdateOne {
	return _u.SetProjectID(v.ID)
}

// AddEventIDs adds the "events" edge to the Event entity by IDs.
func (_u *AgentSessionUpdateOne) AddEventIDs(ids ...int) *AgentSessionUpdateOne {
	_u.mutation.AddEventIDs(ids...)
	return _u
}

// AddEvents adds the "events" edges to the Event entity.
func (_u *AgentSessionUpdateOne) AddEvents(v ...*Event) *AgentSessionUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEventIDs(ids...)
}

// Mutation returns the AgentSessionMutation object of the builder.
func (_u *AgentSessionUpdateOne) Mutation() *AgentSessionMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *AgentSessionUpdateOne) ClearProject() *AgentSessionUpdateOne {
	_u.mutation.ClearProject()
	return _u
}

// ClearEvents clears all "events" edges to the Event entity.
func (_u *AgentSessionUpdateOne) ClearEvents() *AgentSessionUpdateOne {
	_u.mutation.ClearEvents()
	return _u
}

// RemoveEventIDs removes the "events" edge to Event entities by IDs.
func (_u *AgentSessionUpdateOne) RemoveEventIDs(ids ...int) *AgentSessionUpdateOne {
	_u.mutation.RemoveEventIDs(ids...)
	return _u
}

// RemoveEvents removes "events" edges to Event entities.
func (_u *AgentSessionUpdateOne) RemoveEvents(v ...*Event) *AgentSessionUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEventIDs(ids...)
}

// Where appends a list predicates to the AgentSessionUpdate builder.
func (_u *AgentSessionUpdateOne) Where(ps ...predicate.AgentSession) *AgentSessionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AgentSessionUpdateOne) Select(field string, fields ...string) *AgentSessionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AgentSession entity.
func (_u *AgentSessionUpdateOne) Save(ctx context.Context) (*AgentSession, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AgentSessionUpdateOne) SaveX(ctx context.Context) *AgentSession {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AgentSessionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AgentSessionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AgentSessionUpdateOne) check() error {
	if v, ok := _u.mutation.OwnerID(); ok {
		if err := agentsession.OwnerIDValidator(v); err != nil {
			return &ValidationError{Name: "owner_id", err: fmt.Errorf(`ent: validator failed for field "AgentSession.owner_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NextSeq(); ok {
		if err := agentsession.NextSeqValidator(v); err != nil {
			return &ValidationError{Name: "next_seq", err: fmt.Errorf(`ent: validator failed for field "AgentSession.next_seq": %w`, err)}
		}
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AgentSession.project"`)
	}
	return nil
}

func (_u *AgentSessionUpdateOne) sqlSave(ctx context.Context) (_node *AgentSession, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(agentsession.Table, agentsession.Columns, sqlgraph.NewFieldSpec(agentsession.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AgentSession.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, agentsession.FieldID)
		for _, f := range fields {
			if !agentsession.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != agentsession.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OwnerID(); ok {
		_spec.SetField(agentsession.FieldOwnerID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Repo(); ok {
		_spec.SetField(agentsession.FieldRepo, field.TypeString, value)
	}
	if value, ok := _u.mutation.Cwd(); ok {
		_spec.SetField(agentsession.FieldCwd, field.TypeString, value)
	}
	if value, ok := _u.mutation.Harness(); ok {
		_spec.SetField(agentsession.FieldHarness, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(agentsession.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Mode(); ok {
		_spec.SetField(agentsession.FieldMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.NextSeq(); ok {
		_spec.SetField(agentsession.FieldNextSeq, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedNextSeq(); ok {
		_spec.AddField(agentsession.FieldNextSeq, field.TypeInt, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(agentsession.FieldStartedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndedAt(); ok {
		_spec.SetField(agentsession.FieldEndedAt, field.TypeTime, value)
	}
	if _u.mutation.EndedAtCleared() {
		_spec.ClearField(agentsession.FieldEndedAt, field.TypeTime)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentsession.ProjectTable,
			Columns: []string{agentsession.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentsession.ProjectTable,
			Columns: []string{agentsession.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agentsession.EventsTable,
			Columns: []string{agentsession.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEventsIDs(); len(nodes) > 0 && !_u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agentsession.EventsTable,
			Columns: []string{agentsession.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agentsession.EventsTable,
			Columns: []string{agentsession.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AgentSession{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agentsession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
