// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/francogalfre/coop/apps/relay/internal/db/ent/agentsession"
	"github.com/francogalfre/coop/apps/relay/internal/db/ent/event"
	"github.com/francogalfre/coop/apps/relay/internal/db/ent/project"
)

// AgentSessionCreate is the builder for creating a AgentSession entity.
type AgentSessionCreate struct {
	config
	mutation *AgentSessionMutation
	hooks    []Hook
}

// SetOwnerID sets the "owner_id" field.
func (_c *AgentSessionCreate) SetOwnerID(v string) *AgentSessionCreate {
	_c.mutation.SetOwnerID(v)
	return _c
}

// SetRepo sets the "repo" field.
func (_c *AgentSessionCreate) SetRepo(v string) *AgentSessionCreate {
	_c.mutation.SetRepo(v)
	return _c
}

// SetNillableRepo sets the "repo" field if the given value is not nil.
func (_c *AgentSessionCreate) SetNillableRepo(v *string) *AgentSessionCreate {
	if v != nil {
		_c.SetRepo(*v)
	}
	return _c
}

// SetCwd sets the "cwd" field.
func (_c *AgentSessionCreate) SetCwd(v string) *AgentSessionCreate {
	_c.mutation.SetCwd(v)
	return _c
}

// SetNillableCwd sets the "cwd" field if the given value is not nil.
func (_c *AgentSessionCreate) SetNillableCwd(v *string) *AgentSessionCreate {
	if v != nil {
		_c.SetCwd(*v)
	}
	return _c
}

// SetHarness sets the "harness" field.
func (_c *AgentSessionCreate) SetHarness(v string) *AgentSessionCreate {
	_c.mutation.SetHarness(v)
	return _c
}

// SetNillableHarness sets the "harness" field if the given value is not nil.
func (_c *AgentSessionCreate) SetNillableHarness(v *string) *AgentSessionCreate {
	if v != nil {
		_c.SetHarness(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *AgentSessionCreate) SetStatus(v string) *AgentSessionCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *AgentSessionCreate) SetNillableStatus(v *string) *AgentSessionCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetNextSeq sets the "next_seq" field.
func (_c *AgentSessionCreate) SetNextSeq(v int) *AgentSessionCreate {
	_c.mutation.SetNextSeq(v)
	return _c
}

// SetNillableNextSeq sets the "next_seq" field if the given value is not nil.
func (_c *AgentSessionCreate) SetNillableNextSeq(v *int) *AgentSessionCreate {
	if v != nil {
		_c.SetNextSeq(*v)
	}
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *AgentSessionCreate) SetStartedAt(v time.Time) *AgentSessionCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetEndedAt sets the "ended_at" field.
func (_c *AgentSessionCreate) SetEndedAt(v time.Time) *AgentSessionCreate {
	_c.mutation.SetEndedAt(v)
	return _c
}

// SetNillableEndedAt sets the "ended_at" field if the given value is not nil.
func (_c *AgentSessionCreate) SetNillableEndedAt(v *time.Time) *AgentSessionCreate {
	if v != nil {
		_c.SetEndedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AgentSessionCreate) SetID(v string) *AgentSessionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetProjectID sets the "project" edge to the Project entity by ID.
func (_c *AgentSessionCreate) SetProjectID(id int) *AgentSessionCreate {
	_c.mutation.SetProjectID(id)
	return _c
}

// SetProject sets the "project" edge to the Project entity.
func (_c *AgentSessionCreate) SetProject(v *Project) *AgentSessionCreate {
	return _c.SetProjectID(v.ID)
}

// AddEventIDs adds the "events" edge to the Event entity by IDs.
func (_c *AgentSessionCreate) AddEventIDs(ids ...int) *AgentSessionCreate {
	_c.mutation.AddEventIDs(ids...)
	return _c
}

// AddEvents adds the "events" edges to the Event entity.
func (_c *AgentSessionCreate) AddEvents(v ...*Event) *AgentSessionCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddEventIDs(ids...)
}

// Mutation returns the AgentSessionMutation object of the builder.
func (_c *AgentSessionCreate) Mutation() *AgentSessionMutation {
	return _c.mutation
}

// Save creates the AgentSession in the database.
func (_c *AgentSessionCreate) Save(ctx context.Context) (*AgentSession, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AgentSessionCreate) SaveX(ctx context.Context) *AgentSession {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AgentSessionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AgentSessionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AgentSessionCreate) defaults() {
	if _, ok := _c.mutation.Repo(); !ok {
		v := agentsession.DefaultRepo
		_c.mutation.SetRepo(v)
	}
	if _, ok := _c.mutation.Cwd(); !ok {
		v := agentsession.DefaultCwd
		_c.mutation.SetCwd(v)
	}
	if _, ok := _c.mutation.Harness(); !ok {
		v := agentsession.DefaultHarness
		_c.mutation.SetHarness(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := agentsession.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.NextSeq(); !ok {
		v := agentsession.DefaultNextSeq
		_c.mutation.SetNextSeq(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AgentSessionCreate) check() error {
	if _, ok := _c.mutation.OwnerID(); !ok {
		return &ValidationError{Name: "owner_id", err: errors.New(`ent: missing required field "AgentSession.owner_id"`)}
	}
	if v, ok := _c.mutation.OwnerID(); ok {
		if err := agentsession.OwnerIDValidator(v); err != nil {
			return &ValidationError{Name: "owner_id", err: fmt.Errorf(`ent: validator failed for field "AgentSession.owner_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Repo(); !ok {
		return &ValidationError{Name: "repo", err: errors.New(`ent: missing required field "AgentSession.repo"`)}
	}
	if _, ok := _c.mutation.Cwd(); !ok {
		return &ValidationError{Name: "cwd", err: errors.New(`ent: missing required field "AgentSession.cwd"`)}
	}
	if _, ok := _c.mutation.Harness(); !ok {
		return &ValidationError{Name: "harness", err: errors.New(`ent: missing required field "AgentSession.harness"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "AgentSession.status"`)}
	}
	if _, ok := _c.mutation.NextSeq(); !ok {
		return &ValidationError{Name: "next_seq", err: errors.New(`ent: missing required field "AgentSession.next_seq"`)}
	}
	if v, ok := _c.mutation.NextSeq(); ok {
		if err := agentsession.NextSeqValidator(v); err != nil {
			return &ValidationError{Name: "next_seq", err: fmt.Errorf(`ent: validator failed for field "AgentSession.next_seq": %w`, err)}
		}
	}
	if _, ok := _c.mutation.StartedAt(); !ok {
		return &ValidationError{Name: "started_at", err: errors.New(`ent: missing required field "AgentSession.started_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := agentsession.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "AgentSession.id": %w`, err)}
		}
	}
	if len(_c.mutation.ProjectIDs()) == 0 {
		return &ValidationError{Name: "project", err: errors.New(`ent: missing required edge "AgentSession.project"`)}
	}
	return nil
}

func (_c *AgentSessionCreate) sqlSave(ctx context.Context) (*AgentSession, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected AgentSession.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AgentSessionCreate) createSpec() (*AgentSession, *sqlgraph.CreateSpec) {
	var (
		_node = &AgentSession{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(agentsession.Table, sqlgraph.NewFieldSpec(agentsession.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.OwnerID(); ok {
		_spec.SetField(agentsession.FieldOwnerID, field.TypeString, value)
		_node.OwnerID = value
	}
	if value, ok := _c.mutation.Repo(); ok {
		_spec.SetField(agentsession.FieldRepo, field.TypeString, value)
		_node.Repo = value
	}
	if value, ok := _c.mutation.Cwd(); ok {
		_spec.SetField(agentsession.FieldCwd, field.TypeString, value)
		_node.Cwd = value
	}
	if value, ok := _c.mutation.Harness(); ok {
		_spec.SetField(agentsession.FieldHarness, field.TypeString, value)
		_node.Harness = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(agentsession.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.NextSeq(); ok {
		_spec.SetField(agentsession.FieldNextSeq, field.TypeInt, value)
		_node.NextSeq = value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(agentsession.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = value
	}
	if value, ok := _c.mutation.EndedAt(); ok {
		_spec.SetField(agentsession.FieldEndedAt, field.TypeTime, value)
		_node.EndedAt = &value
	}
	if nodes := _c.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentsession.ProjectTable,
			Columns: []string{agentsession.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.project_sessions = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.EventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agentsession.EventsTable,
			Columns: []string{agentsession.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AgentSessionCreateBulk is the builder for creating many AgentSession entities in bulk.
type AgentSessionCreateBulk struct {
	config
	err      error
	builders []*AgentSessionCreate
}

// Save creates the AgentSession entities in the database.
func (_c *AgentSessionCreateBulk) Save(ctx context.Context) ([]*AgentSession, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AgentSession, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AgentSessionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AgentSessionCreateBulk) SaveX(ctx context.Context) []*AgentSession {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AgentSessionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AgentSessionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
