// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/francogalfre/coop/apps/relay/internal/db/ent/agent"
	"github.com/francogalfre/coop/apps/relay/internal/db/ent/agentsession"
	"github.com/francogalfre/coop/apps/relay/internal/db/ent/project"
)

// AgentSession is the model entity for the AgentSession schema.
type AgentSession struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// OwnerID holds the value of the "owner_id" field.
	OwnerID string `json:"owner_id,omitempty"`
	// Repo holds the value of the "repo" field.
	Repo string `json:"repo,omitempty"`
	// Cwd holds the value of the "cwd" field.
	Cwd string `json:"cwd,omitempty"`
	// Harness holds the value of the "harness" field.
	Harness string `json:"harness,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Mode holds the value of the "mode" field.
	Mode string `json:"mode,omitempty"`
	// NextSeq holds the value of the "next_seq" field.
	NextSeq int `json:"next_seq,omitempty"`
	// StartedAt holds the value of the "started_at" field.
	StartedAt time.Time `json:"started_at,omitempty"`
	// EndedAt holds the value of the "ended_at" field.
	EndedAt *time.Time `json:"ended_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AgentSessionQuery when eager-loading is set.
	Edges            AgentSessionEdges `json:"edges"`
	agent_sessions   *string
	project_sessions *int
	selectValues     sql.SelectValues
}

// AgentSessionEdges holds the relations/edges for other nodes in the graph.
type AgentSessionEdges struct {
	// Project holds the value of the project edge.
	Project *Project `json:"project,omitempty"`
	// Agent holds the value of the agent edge.
	Agent *Agent `json:"agent,omitempty"`
	// Events holds the value of the events edge.
	Events []*Event `json:"events,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// ProjectOrErr returns the Project value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AgentSessionEdges) ProjectOrErr() (*Project, error) {
	if e.Project != nil {
		return e.Project, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: project.Label}
	}
	return nil, &NotLoadedError{edge: "project"}
}

// AgentOrErr returns the Agent value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AgentSessionEdges) AgentOrErr() (*Agent, error) {
	if e.Agent != nil {
		return e.Agent, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: agent.Label}
	}
	return nil, &NotLoadedError{edge: "agent"}
}

// EventsOrErr returns the Events value or an error if the edge
// was not loaded in eager-loading.
func (e AgentSessionEdges) EventsOrErr() ([]*Event, error) {
	if e.loadedTypes[2] {
		return e.Events, nil
	}
	return nil, &NotLoadedError{edge: "events"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AgentSession) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case agentsession.FieldNextSeq:
			values[i] = new(sql.NullInt64)
		case agentsession.FieldID, agentsession.FieldOwnerID, agentsession.FieldRepo, agentsession.FieldCwd, agentsession.FieldHarness, agentsession.FieldStatus, agentsession.FieldMode:
			values[i] = new(sql.NullString)
		case agentsession.FieldStartedAt, agentsession.FieldEndedAt:
			values[i] = new(sql.NullTime)
		case agentsession.ForeignKeys[0]: // agent_sessions
			values[i] = new(sql.NullString)
		case agentsession.ForeignKeys[1]: // project_sessions
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AgentSession fields.
func (_m *AgentSession) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case agentsession.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case agentsession.FieldOwnerID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field owner_id", values[i])
			} else if value.Valid {
				_m.OwnerID = value.String
			}
		case agentsession.FieldRepo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field repo", values[i])
			} else if value.Valid {
				_m.Repo = value.String
			}
		case agentsession.FieldCwd:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cwd", values[i])
			} else if value.Valid {
				_m.Cwd = value.String
			}
		case agentsession.FieldHarness:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field harness", values[i])
			} else if value.Valid {
				_m.Harness = value.String
			}
		case agentsession.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case agentsession.FieldMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mode", values[i])
			} else if value.Valid {
				_m.Mode = value.String
			}
		case agentsession.FieldNextSeq:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field next_seq", values[i])
			} else if value.Valid {
				_m.NextSeq = int(value.Int64)
			}
		case agentsession.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = value.Time
			}
		case agentsession.FieldEndedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field ended_at", values[i])
			} else if value.Valid {
				_m.EndedAt = new(time.Time)
				*_m.EndedAt = value.Time
			}
		case agentsession.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field agent_sessions", values[i])
			} else if value.Valid {
				_m.agent_sessions = new(string)
				*_m.agent_sessions = value.String
			}
		case agentsession.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field project_sessions", value)
			} else if value.Valid {
				_m.project_sessions = new(int)
				*_m.project_sessions = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AgentSession.
// This includes values selected through modifiers, order, etc.
func (_m *AgentSession) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProject queries the "project" edge of the AgentSession entity.
func (_m *AgentSession) QueryProject() *ProjectQuery {
	return NewAgentSessionClient(_m.config).QueryProject(_m)
}

// QueryAgent queries the "agent" edge of the AgentSession entity.
func (_m *AgentSession) QueryAgent() *AgentQuery {
	return NewAgentSessionClient(_m.config).QueryAgent(_m)
}

// QueryEvents queries the "events" edge of the AgentSession entity.
func (_m *AgentSession) QueryEvents() *EventQuery {
	return NewAgentSessionClient(_m.config).QueryEvents(_m)
}

// Update returns a builder for updating this AgentSession.
// Note that you need to call AgentSession.Unwrap() before calling this method if this AgentSession
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AgentSession) Update() *AgentSessionUpdateOne {
	return NewAgentSessionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AgentSession entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AgentSession) Unwrap() *AgentSession {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AgentSession is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AgentSession) String() string {
	var builder strings.Builder
	builder.WriteString("AgentSession(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("owner_id=")
	builder.WriteString(_m.OwnerID)
	builder.WriteString(", ")
	builder.WriteString("repo=")
	builder.WriteString(_m.Repo)
	builder.WriteString(", ")
	builder.WriteString("cwd=")
	builder.WriteString(_m.Cwd)
	builder.WriteString(", ")
	builder.WriteString("harness=")
	builder.WriteString(_m.Harness)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("mode=")
	builder.WriteString(_m.Mode)
	builder.WriteString(", ")
	builder.WriteString("next_seq=")
	builder.WriteString(fmt.Sprintf("%v", _m.NextSeq))
	builder.WriteString(", ")
	builder.WriteString("started_at=")
	builder.WriteString(_m.StartedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.EndedAt; v != nil {
		builder.WriteString("ended_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// AgentSessions is a parsable slice of AgentSession.
type AgentSessions []*AgentSession
