// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/francogalfre/coop/apps/relay/internal/db/ent/clicredential"
	"github.com/francogalfre/coop/apps/relay/internal/db/ent/predicate"
)

// CliCredentialUpdate is the builder for updating CliCredential entities.
type CliCredentialUpdate struct {
	config
	hooks    []Hook
	mutation *CliCredentialMutation
}

// Where appends a list predicates to the CliCredentialUpdate builder.
func (_u *CliCredentialUpdate) Where(ps ...predicate.CliCredential) *CliCredentialUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *CliCredentialUpdate) SetUserID(v string) *CliCredentialUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CliCredentialUpdate) SetNillableUserID(v *string) *CliCredentialUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetTokenHash sets the "token_hash" field.
func (_u *CliCredentialUpdate) SetTokenHash(v []byte) *CliCredentialUpdate {
	_u.mutation.SetTokenHash(v)
	return _u
}

// SetLastUsedAt sets the "last_used_at" field.
func (_u *CliCredentialUpdate) SetLastUsedAt(v time.Time) *CliCredentialUpdate {
	_u.mutation.SetLastUsedAt(v)
	return _u
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_u *CliCredentialUpdate) SetNillableLastUsedAt(v *time.Time) *CliCredentialUpdate {
	if v != nil {
		_u.SetLastUsedAt(*v)
	}
	return _u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (_u *CliCredentialUpdate) ClearLastUsedAt() *CliCredentialUpdate {
	_u.mutation.ClearLastUsedAt()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *CliCredentialUpdate) SetExpiresAt(v time.Time) *CliCredentialUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *CliCredentialUpdate) SetNillableExpiresAt(v *time.Time) *CliCredentialUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *CliCredentialUpdate) ClearExpiresAt() *CliCredentialUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// Mutation returns the CliCredentialMutation object of the builder.
func (_u *CliCredentialUpdate) Mutation() *CliCredentialMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CliCredentialUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CliCredentialUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CliCredentialUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CliCredentialUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CliCredentialUpdate) check() error {
	if v, ok := _u.mutation.UserID(); ok {
		if err := clicredential.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "CliCredential.user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TokenHash(); ok {
		if err := clicredential.TokenHashValidator(v); err != nil {
			return &ValidationError{Name: "token_hash", err: fmt.Errorf(`ent: validator failed for field "CliCredential.token_hash": %w`, err)}
		}
	}
	return nil
}

func (_u *CliCredentialUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(clicredential.Table, clicredential.Columns, sqlgraph.NewFieldSpec(clicredential.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(clicredential.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.TokenHash(); ok {
		_spec.SetField(clicredential.FieldTokenHash, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.LastUsedAt(); ok {
		_spec.SetField(clicredential.FieldLastUsedAt, field.TypeTime, value)
	}
	if _u.mutation.LastUsedAtCleared() {
		_spec.ClearField(clicredential.FieldLastUsedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(clicredential.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(clicredential.FieldExpiresAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{clicredential.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CliCredentialUpdateOne is the builder for updating a single CliCredential entity.
type CliCredentialUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CliCredentialMutation
}

// SetUserID sets the "user_id" field.
func (_u *CliCredentialUpdateOne) SetUserID(v string) *CliCredentialUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CliCredentialUpdateOne) SetNillableUserID(v *string) *CliCredentialUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetTokenHash sets the "token_hash" field.
func (_u *CliCredentialUpdateOne) SetTokenHash(v []byte) *CliCredentialUpdateOne {
	_u.mutation.SetTokenHash(v)
	return _u
}

// SetLastUsedAt sets the "last_used_at" field.
func (_u *CliCredentialUpdateOne) SetLastUsedAt(v time.Time) *CliCredentialUpdateOne {
	_u.mutation.SetLastUsedAt(v)
	return _u
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_u *CliCredentialUpdateOne) SetNillableLastUsedAt(v *time.Time) *CliCredentialUpdateOne {
	if v != nil {
		_u.SetLastUsedAt(*v)
	}
	return _u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (_u *CliCredentialUpdateOne) ClearLastUsedAt() *CliCredentialUpdateOne {
	_u.mutation.ClearLastUsedAt()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *CliCredentialUpdateOne) SetExpiresAt(v time.Time) *CliCredentialUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *CliCredentialUpdateOne) SetNillableExpiresAt(v *time.Time) *CliCredentialUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *CliCredentialUpdateOne) ClearExpiresAt() *CliCredentialUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// Mutation returns the CliCredentialMutation object of the builder.
func (_u *CliCredentialUpdateOne) Mutation() *CliCredentialMutation {
	return _u.mutation
}

// Where appends a list predicates to the CliCredentialUpdate builder.
func (_u *CliCredentialUpdateOne) Where(ps ...predicate.CliCredential) *CliCredentialUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CliCredentialUpdateOne) Select(field string, fields ...string) *CliCredentialUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CliCredential entity.
func (_u *CliCredentialUpdateOne) Save(ctx context.Context) (*CliCredential, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CliCredentialUpdateOne) SaveX(ctx context.Context) *CliCredential {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CliCredentialUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CliCredentialUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CliCredentialUpdateOne) check() error {
	if v, ok := _u.mutation.UserID(); ok {
		if err := clicredential.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "CliCredential.user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TokenHash(); ok {
		if err := clicredential.TokenHashValidator(v); err != nil {
			return &ValidationError{Name: "token_hash", err: fmt.Errorf(`ent: validator failed for field "CliCredential.token_hash": %w`, err)}
		}
	}
	return nil
}

func (_u *CliCredentialUpdateOne) sqlSave(ctx context.Context) (_node *CliCredential, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(clicredential.Table, clicredential.Columns, sqlgraph.NewFieldSpec(clicredential.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CliCredential.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, clicredential.FieldID)
		for _, f := range fields {
			if !clicredential.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != clicredential.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(clicredential.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.TokenHash(); ok {
		_spec.SetField(clicredential.FieldTokenHash, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.LastUsedAt(); ok {
		_spec.SetField(clicredential.FieldLastUsedAt, field.TypeTime, value)
	}
	if _u.mutation.LastUsedAtCleared() {
		_spec.ClearField(clicredential.FieldLastUsedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(clicredential.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(clicredential.FieldExpiresAt, field.TypeTime)
	}
	_node = &CliCredential{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{clicredential.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
