// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/francogalfre/coop/apps/relay/internal/db/ent/clicredential"
)

// CliCredentialCreate is the builder for creating a CliCredential entity.
type CliCredentialCreate struct {
	config
	mutation *CliCredentialMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *CliCredentialCreate) SetUserID(v string) *CliCredentialCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetDisplayName sets the "display_name" field.
func (_c *CliCredentialCreate) SetDisplayName(v string) *CliCredentialCreate {
	_c.mutation.SetDisplayName(v)
	return _c
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_c *CliCredentialCreate) SetNillableDisplayName(v *string) *CliCredentialCreate {
	if v != nil {
		_c.SetDisplayName(*v)
	}
	return _c
}

// SetTokenHash sets the "token_hash" field.
func (_c *CliCredentialCreate) SetTokenHash(v []byte) *CliCredentialCreate {
	_c.mutation.SetTokenHash(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CliCredentialCreate) SetCreatedAt(v time.Time) *CliCredentialCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CliCredentialCreate) SetNillableCreatedAt(v *time.Time) *CliCredentialCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetLastUsedAt sets the "last_used_at" field.
func (_c *CliCredentialCreate) SetLastUsedAt(v time.Time) *CliCredentialCreate {
	_c.mutation.SetLastUsedAt(v)
	return _c
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_c *CliCredentialCreate) SetNillableLastUsedAt(v *time.Time) *CliCredentialCreate {
	if v != nil {
		_c.SetLastUsedAt(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *CliCredentialCreate) SetExpiresAt(v time.Time) *CliCredentialCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *CliCredentialCreate) SetNillableExpiresAt(v *time.Time) *CliCredentialCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// Mutation returns the CliCredentialMutation object of the builder.
func (_c *CliCredentialCreate) Mutation() *CliCredentialMutation {
	return _c.mutation
}

// Save creates the CliCredential in the database.
func (_c *CliCredentialCreate) Save(ctx context.Context) (*CliCredential, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CliCredentialCreate) SaveX(ctx context.Context) *CliCredential {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CliCredentialCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CliCredentialCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CliCredentialCreate) defaults() {
	if _, ok := _c.mutation.DisplayName(); !ok {
		v := clicredential.DefaultDisplayName
		_c.mutation.SetDisplayName(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := clicredential.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CliCredentialCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "CliCredential.user_id"`)}
	}
	if v, ok := _c.mutation.UserID(); ok {
		if err := clicredential.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "CliCredential.user_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DisplayName(); !ok {
		return &ValidationError{Name: "display_name", err: errors.New(`ent: missing required field "CliCredential.display_name"`)}
	}
	if _, ok := _c.mutation.TokenHash(); !ok {
		return &ValidationError{Name: "token_hash", err: errors.New(`ent: missing required field "CliCredential.token_hash"`)}
	}
	if v, ok := _c.mutation.TokenHash(); ok {
		if err := clicredential.TokenHashValidator(v); err != nil {
			return &ValidationError{Name: "token_hash", err: fmt.Errorf(`ent: validator failed for field "CliCredential.token_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CliCredential.created_at"`)}
	}
	return nil
}

func (_c *CliCredentialCreate) sqlSave(ctx context.Context) (*CliCredential, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CliCredentialCreate) createSpec() (*CliCredential, *sqlgraph.CreateSpec) {
	var (
		_node = &CliCredential{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(clicredential.Table, sqlgraph.NewFieldSpec(clicredential.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(clicredential.FieldUserID, field.TypeString, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.DisplayName(); ok {
		_spec.SetField(clicredential.FieldDisplayName, field.TypeString, value)
		_node.DisplayName = value
	}
	if value, ok := _c.mutation.TokenHash(); ok {
		_spec.SetField(clicredential.FieldTokenHash, field.TypeBytes, value)
		_node.TokenHash = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(clicredential.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.LastUsedAt(); ok {
		_spec.SetField(clicredential.FieldLastUsedAt, field.TypeTime, value)
		_node.LastUsedAt = &value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(clicredential.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	return _node, _spec
}

// CliCredentialCreateBulk is the builder for creating many CliCredential entities in bulk.
type CliCredentialCreateBulk struct {
	config
	err      error
	builders []*CliCredentialCreate
}

// Save creates the CliCredential entities in the database.
func (_c *CliCredentialCreateBulk) Save(ctx context.Context) ([]*CliCredential, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CliCredential, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CliCredentialMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CliCredentialCreateBulk) SaveX(ctx context.Context) []*CliCredential {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CliCredentialCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CliCredentialCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
