// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/francogalfre/coop/apps/relay/internal/db/ent/predicate"
	"github.com/francogalfre/coop/apps/relay/internal/db/ent/project"
	"github.com/francogalfre/coop/apps/relay/internal/db/ent/projectinvite"
)

// ProjectInviteUpdate is the builder for updating ProjectInvite entities.
type ProjectInviteUpdate struct {
	config
	hooks    []Hook
	mutation *ProjectInviteMutation
}

// Where appends a list predicates to the ProjectInviteUpdate builder.
func (_u *ProjectInviteUpdate) Where(ps ...predicate.ProjectInvite) *ProjectInviteUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTokenHash sets the "token_hash" field.
func (_u *ProjectInviteUpdate) SetTokenHash(v []byte) *ProjectInviteUpdate {
	_u.mutation.SetTokenHash(v)
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *ProjectInviteUpdate) SetCreatedBy(v string) *ProjectInviteUpdate {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *ProjectInviteUpdate) SetNillableCreatedBy(v *string) *ProjectInviteUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *ProjectInviteUpdate) SetExpiresAt(v time.Time) *ProjectInviteUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *ProjectInviteUpdate) SetNillableExpiresAt(v *time.Time) *ProjectInviteUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *ProjectInviteUpdate) SetRevokedAt(v time.Time) *ProjectInviteUpdate {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *ProjectInviteUpdate) SetNillableRevokedAt(v *time.Time) *ProjectInviteUpdate {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *ProjectInviteUpdate) ClearRevokedAt() *ProjectInviteUpdate {
	_u.mutation.ClearRevokedAt()
	return _u
}

// SetProjectID sets the "project" edge to the Project entity by ID.
func (_u *ProjectInviteUpdate) SetProjectID(id int) *ProjectInviteUpdate {
	_u.mutation.SetProjectID(id)
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *ProjectInviteUpdate) SetProject(v *Project) *ProjectInviteUpdate {
	return _u.SetProjectID(v.ID)
}

// Mutation returns the ProjectInviteMutation object of the builder.
func (_u *ProjectInviteUpdate) Mutation() *ProjectInviteMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *ProjectInviteUpdate) ClearProject() *ProjectInviteUpdate {
	_u.mutation.ClearProject()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProjectInviteUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProjectInviteUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProjectInviteUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProjectInviteUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProjectInviteUpdate) check() error {
	if v, ok := _u.mutation.TokenHash(); ok {
		if err := projectinvite.TokenHashValidator(v); err != nil {
			return &ValidationError{Name: "token_hash", err: fmt.Errorf(`ent: validator failed for field "ProjectInvite.token_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CreatedBy(); ok {
		if err := projectinvite.CreatedByValidator(v); err != nil {
			return &ValidationError{Name: "created_by", err: fmt.Errorf(`ent: validator failed for field "ProjectInvite.created_by": %w`, err)}
		}
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProjectInvite.project"`)
	}
	return nil
}

func (_u *ProjectInviteUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(projectinvite.Table, projectinvite.Columns, sqlgraph.NewFieldSpec(projectinvite.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TokenHash(); ok {
		_spec.SetField(projectinvite.FieldTokenHash, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(projectinvite.FieldCreatedBy, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(projectinvite.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(projectinvite.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(projectinvite.FieldRevokedAt, field.TypeTime)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projectinvite.ProjectTable,
			Columns: []string{projectinvite.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projectinvite.ProjectTable,
			Columns: []string{projectinvite.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{projectinvite.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProjectInviteUpdateOne is the builder for updating a single ProjectInvite entity.
type ProjectInviteUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProjectInviteMutation
}

// SetTokenHash sets the "token_hash" field.
func (_u *ProjectInviteUpdateOne) SetTokenHash(v []byte) *ProjectInviteUpdateOne {
	_u.mutation.SetTokenHash(v)
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *ProjectInviteUpdateOne) SetCreatedBy(v string) *ProjectInviteUpdateOne {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *ProjectInviteUpdateOne) SetNillableCreatedBy(v *string) *ProjectInviteUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *ProjectInviteUpdateOne) SetExpiresAt(v time.Time) *ProjectInviteUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *ProjectInviteUpdateOne) SetNillableExpiresAt(v *time.Time) *ProjectInviteUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *ProjectInviteUpdateOne) SetRevokedAt(v time.Time) *ProjectInviteUpdateOne {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *ProjectInviteUpdateOne) SetNillableRevokedAt(v *time.Time) *ProjectInviteUpdateOne {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *ProjectInviteUpdateOne) ClearRevokedAt() *ProjectInviteUpdateOne {
	_u.mutation.ClearRevokedAt()
	return _u
}

// SetProjectID sets the "project" edge to the Project entity by ID.
func (_u *ProjectInviteUpdateOne) SetProjectID(id int) *ProjectInviteUpdateOne {
	_u.mutation.SetProjectID(id)
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *ProjectInviteUpdateOne) SetProject(v *Project) *ProjectInviteUpdateOne {
	return _u.SetProjectID(v.ID)
}

// Mutation returns the ProjectInviteMutation object of the builder.
func (_u *ProjectInviteUpdateOne) Mutation() *ProjectInviteMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *ProjectInviteUpdateOne) ClearProject() *ProjectInviteUpdateOne {
	_u.mutation.ClearProject()
	return _u
}

// Where appends a list predicates to the ProjectInviteUpdate builder.
func (_u *ProjectInviteUpdateOne) Where(ps ...predicate.ProjectInvite) *ProjectInviteUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProjectInviteUpdateOne) Select(field string, fields ...string) *ProjectInviteUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ProjectInvite entity.
func (_u *ProjectInviteUpdateOne) Save(ctx context.Context) (*ProjectInvite, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProjectInviteUpdateOne) SaveX(ctx context.Context) *ProjectInvite {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProjectInviteUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProjectInviteUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProjectInviteUpdateOne) check() error {
	if v, ok := _u.mutation.TokenHash(); ok {
		if err := projectinvite.TokenHashValidator(v); err != nil {
			return &ValidationError{Name: "token_hash", err: fmt.Errorf(`ent: validator failed for field "ProjectInvite.token_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CreatedBy(); ok {
		if err := projectinvite.CreatedByValidator(v); err != nil {
			return &ValidationError{Name: "created_by", err: fmt.Errorf(`ent: validator failed for field "ProjectInvite.created_by": %w`, err)}
		}
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProjectInvite.project"`)
	}
	return nil
}

func (_u *ProjectInviteUpdateOne) sqlSave(ctx context.Context) (_node *ProjectInvite, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(projectinvite.Table, projectinvite.Columns, sqlgraph.NewFieldSpec(projectinvite.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProjectInvite.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, projectinvite.FieldID)
		for _, f := range fields {
			if !projectinvite.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != projectinvite.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TokenHash(); ok {
		_spec.SetField(projectinvite.FieldTokenHash, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(projectinvite.FieldCreatedBy, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(projectinvite.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(projectinvite.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(projectinvite.FieldRevokedAt, field.TypeTime)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projectinvite.ProjectTable,
			Columns: []string{projectinvite.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projectinvite.ProjectTable,
			Columns: []string{projectinvite.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ProjectInvite{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{projectinvite.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
