// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/francogalfre/coop/apps/relay/internal/db/ent/project"
	"github.com/francogalfre/coop/apps/relay/internal/db/ent/projectnote"
)

// ProjectNoteCreate is the builder for creating a ProjectNote entity.
type ProjectNoteCreate struct {
	config
	mutation *ProjectNoteMutation
	hooks    []Hook
}

// SetAuthorID sets the "author_id" field.
func (_c *ProjectNoteCreate) SetAuthorID(v string) *ProjectNoteCreate {
	_c.mutation.SetAuthorID(v)
	return _c
}

// SetAuthorDisplayName sets the "author_display_name" field.
func (_c *ProjectNoteCreate) SetAuthorDisplayName(v string) *ProjectNoteCreate {
	_c.mutation.SetAuthorDisplayName(v)
	return _c
}

// SetNillableAuthorDisplayName sets the "author_display_name" field if the given value is not nil.
func (_c *ProjectNoteCreate) SetNillableAuthorDisplayName(v *string) *ProjectNoteCreate {
	if v != nil {
		_c.SetAuthorDisplayName(*v)
	}
	return _c
}

// SetAuthorAvatarURL sets the "author_avatar_url" field.
func (_c *ProjectNoteCreate) SetAuthorAvatarURL(v string) *ProjectNoteCreate {
	_c.mutation.SetAuthorAvatarURL(v)
	return _c
}

// SetNillableAuthorAvatarURL sets the "author_avatar_url" field if the given value is not nil.
func (_c *ProjectNoteCreate) SetNillableAuthorAvatarURL(v *string) *ProjectNoteCreate {
	if v != nil {
		_c.SetAuthorAvatarURL(*v)
	}
	return _c
}

// SetSource sets the "source" field.
func (_c *ProjectNoteCreate) SetSource(v string) *ProjectNoteCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_c *ProjectNoteCreate) SetNillableSource(v *string) *ProjectNoteCreate {
	if v != nil {
		_c.SetSource(*v)
	}
	return _c
}

// SetSessionID sets the "session_id" field.
func (_c *ProjectNoteCreate) SetSessionID(v string) *ProjectNoteCreate {
	_c.mutation.SetSessionID(v)
	return _c
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_c *ProjectNoteCreate) SetNillableSessionID(v *string) *ProjectNoteCreate {
	if v != nil {
		_c.SetSessionID(*v)
	}
	return _c
}

// SetText sets the "text" field.
func (_c *ProjectNoteCreate) SetText(v string) *ProjectNoteCreate {
	_c.mutation.SetText(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ProjectNoteCreate) SetCreatedAt(v time.Time) *ProjectNoteCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ProjectNoteCreate) SetNillableCreatedAt(v *time.Time) *ProjectNoteCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ProjectNoteCreate) SetID(v string) *ProjectNoteCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetProjectID sets the "project" edge to the Project entity by ID.
func (_c *ProjectNoteCreate) SetProjectID(id int) *ProjectNoteCreate {
	_c.mutation.SetProjectID(id)
	return _c
}

// SetProject sets the "project" edge to the Project entity.
func (_c *ProjectNoteCreate) SetProject(v *Project) *ProjectNoteCreate {
	return _c.SetProjectID(v.ID)
}

// Mutation returns the ProjectNoteMutation object of the builder.
func (_c *ProjectNoteCreate) Mutation() *ProjectNoteMutation {
	return _c.mutation
}

// Save creates the ProjectNote in the database.
func (_c *ProjectNoteCreate) Save(ctx context.Context) (*ProjectNote, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProjectNoteCreate) SaveX(ctx context.Context) *ProjectNote {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProjectNoteCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProjectNoteCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ProjectNoteCreate) defaults() {
	if _, ok := _c.mutation.AuthorDisplayName(); !ok {
		v := projectnote.DefaultAuthorDisplayName
		_c.mutation.SetAuthorDisplayName(v)
	}
	if _, ok := _c.mutation.AuthorAvatarURL(); !ok {
		v := projectnote.DefaultAuthorAvatarURL
		_c.mutation.SetAuthorAvatarURL(v)
	}
	if _, ok := _c.mutation.Source(); !ok {
		v := projectnote.DefaultSource
		_c.mutation.SetSource(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := projectnote.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProjectNoteCreate) check() error {
	if _, ok := _c.mutation.AuthorID(); !ok {
		return &ValidationError{Name: "author_id", err: errors.New(`ent: missing required field "ProjectNote.author_id"`)}
	}
	if v, ok := _c.mutation.AuthorID(); ok {
		if err := projectnote.AuthorIDValidator(v); err != nil {
			return &ValidationError{Name: "author_id", err: fmt.Errorf(`ent: validator failed for field "ProjectNote.author_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AuthorDisplayName(); !ok {
		return &ValidationError{Name: "author_display_name", err: errors.New(`ent: missing required field "ProjectNote.author_display_name"`)}
	}
	if _, ok := _c.mutation.AuthorAvatarURL(); !ok {
		return &ValidationError{Name: "author_avatar_url", err: errors.New(`ent: missing required field "ProjectNote.author_avatar_url"`)}
	}
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "ProjectNote.source"`)}
	}
	if _, ok := _c.mutation.Text(); !ok {
		return &ValidationError{Name: "text", err: errors.New(`ent: missing required field "ProjectNote.text"`)}
	}
	if v, ok := _c.mutation.Text(); ok {
		if err := projectnote.TextValidator(v); err != nil {
			return &ValidationError{Name: "text", err: fmt.Errorf(`ent: validator failed for field "ProjectNote.text": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ProjectNote.created_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := projectnote.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "ProjectNote.id": %w`, err)}
		}
	}
	if len(_c.mutation.ProjectIDs()) == 0 {
		return &ValidationError{Name: "project", err: errors.New(`ent: missing required edge "ProjectNote.project"`)}
	}
	return nil
}

func (_c *ProjectNoteCreate) sqlSave(ctx context.Context) (*ProjectNote, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected ProjectNote.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ProjectNoteCreate) createSpec() (*ProjectNote, *sqlgraph.CreateSpec) {
	var (
		_node = &ProjectNote{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(projectnote.Table, sqlgraph.NewFieldSpec(projectnote.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.AuthorID(); ok {
		_spec.SetField(projectnote.FieldAuthorID, field.TypeString, value)
		_node.AuthorID = value
	}
	if value, ok := _c.mutation.AuthorDisplayName(); ok {
		_spec.SetField(projectnote.FieldAuthorDisplayName, field.TypeString, value)
		_node.AuthorDisplayName = value
	}
	if value, ok := _c.mutation.AuthorAvatarURL(); ok {
		_spec.SetField(projectnote.FieldAuthorAvatarURL, field.TypeString, value)
		_node.AuthorAvatarURL = value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(projectnote.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.SessionID(); ok {
		_spec.SetField(projectnote.FieldSessionID, field.TypeString, value)
		_node.SessionID = value
	}
	if value, ok := _c.mutation.Text(); ok {
		_spec.SetField(projectnote.FieldText, field.TypeString, value)
		_node.Text = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(projectnote.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projectnote.ProjectTable,
			Columns: []string{projectnote.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.project_notes = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ProjectNoteCreateBulk is the builder for creating many ProjectNote entities in bulk.
type ProjectNoteCreateBulk struct {
	config
	err      error
	builders []*ProjectNoteCreate
}

// Save creates the ProjectNote entities in the database.
func (_c *ProjectNoteCreateBulk) Save(ctx context.Context) ([]*ProjectNote, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ProjectNote, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProjectNoteMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProjectNoteCreateBulk) SaveX(ctx context.Context) []*ProjectNote {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProjectNoteCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProjectNoteCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
