// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/francogalfre/coop/apps/relay/internal/db/ent/project"
)

// Project is the model entity for the Project schema.
type Project struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Slug holds the value of the "slug" field.
	Slug string `json:"slug,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy string `json:"created_by,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// ContextText holds the value of the "context_text" field.
	ContextText string `json:"context_text,omitempty"`
	// ContextVersion holds the value of the "context_version" field.
	ContextVersion int `json:"context_version,omitempty"`
	// ContextUpdatedBy holds the value of the "context_updated_by" field.
	ContextUpdatedBy string `json:"context_updated_by,omitempty"`
	// ContextUpdatedAt holds the value of the "context_updated_at" field.
	ContextUpdatedAt *time.Time `json:"context_updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ProjectQuery when eager-loading is set.
	Edges        ProjectEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ProjectEdges holds the relations/edges for other nodes in the graph.
type ProjectEdges struct {
	// Members holds the value of the members edge.
	Members []*ProjectMember `json:"members,omitempty"`
	// Invites holds the value of the invites edge.
	Invites []*ProjectInvite `json:"invites,omitempty"`
	// Sessions holds the value of the sessions edge.
	Sessions []*AgentSession `json:"sessions,omitempty"`
	// Agents holds the value of the agents edge.
	Agents []*Agent `json:"agents,omitempty"`
	// Notes holds the value of the notes edge.
	Notes []*ProjectNote `json:"notes,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [5]bool
}

// MembersOrErr returns the Members value or an error if the edge
// was not loaded in eager-loading.
func (e ProjectEdges) MembersOrErr() ([]*ProjectMember, error) {
	if e.loadedTypes[0] {
		return e.Members, nil
	}
	return nil, &NotLoadedError{edge: "members"}
}

// InvitesOrErr returns the Invites value or an error if the edge
// was not loaded in eager-loading.
func (e ProjectEdges) InvitesOrErr() ([]*ProjectInvite, error) {
	if e.loadedTypes[1] {
		return e.Invites, nil
	}
	return nil, &NotLoadedError{edge: "invites"}
}

// SessionsOrErr returns the Sessions value or an error if the edge
// was not loaded in eager-loading.
func (e ProjectEdges) SessionsOrErr() ([]*AgentSession, error) {
	if e.loadedTypes[2] {
		return e.Sessions, nil
	}
	return nil, &NotLoadedError{edge: "sessions"}
}

// AgentsOrErr returns the Agents value or an error if the edge
// was not loaded in eager-loading.
func (e ProjectEdges) AgentsOrErr() ([]*Agent, error) {
	if e.loadedTypes[3] {
		return e.Agents, nil
	}
	return nil, &NotLoadedError{edge: "agents"}
}

// NotesOrErr returns the Notes value or an error if the edge
// was not loaded in eager-loading.
func (e ProjectEdges) NotesOrErr() ([]*ProjectNote, error) {
	if e.loadedTypes[4] {
		return e.Notes, nil
	}
	return nil, &NotLoadedError{edge: "notes"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Project) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case project.FieldID, project.FieldContextVersion:
			values[i] = new(sql.NullInt64)
		case project.FieldName, project.FieldSlug, project.FieldCreatedBy, project.FieldContextText, project.FieldContextUpdatedBy:
			values[i] = new(sql.NullString)
		case project.FieldCreatedAt, project.FieldContextUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Project fields.
func (_m *Project) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case project.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case project.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case project.FieldSlug:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field slug", values[i])
			} else if value.Valid {
				_m.Slug = value.String
			}
		case project.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = value.String
			}
		case project.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case project.FieldContextText:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field context_text", values[i])
			} else if value.Valid {
				_m.ContextText = value.String
			}
		case project.FieldContextVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field context_version", values[i])
			} else if value.Valid {
				_m.ContextVersion = int(value.Int64)
			}
		case project.FieldContextUpdatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field context_updated_by", values[i])
			} else if value.Valid {
				_m.ContextUpdatedBy = value.String
			}
		case project.FieldContextUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field context_updated_at", values[i])
			} else if value.Valid {
				_m.ContextUpdatedAt = new(time.Time)
				*_m.ContextUpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Project.
// This includes values selected through modifiers, order, etc.
func (_m *Project) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryMembers queries the "members" edge of the Project entity.
func (_m *Project) QueryMembers() *ProjectMemberQuery {
	return NewProjectClient(_m.config).QueryMembers(_m)
}

// QueryInvites queries the "invites" edge of the Project entity.
func (_m *Project) QueryInvites() *ProjectInviteQuery {
	return NewProjectClient(_m.config).QueryInvites(_m)
}

// QuerySessions queries the "sessions" edge of the Project entity.
func (_m *Project) QuerySessions() *AgentSessionQuery {
	return NewProjectClient(_m.config).QuerySessions(_m)
}

// QueryAgents queries the "agents" edge of the Project entity.
func (_m *Project) QueryAgents() *AgentQuery {
	return NewProjectClient(_m.config).QueryAgents(_m)
}

// QueryNotes queries the "notes" edge of the Project entity.
func (_m *Project) QueryNotes() *ProjectNoteQuery {
	return NewProjectClient(_m.config).QueryNotes(_m)
}

// Update returns a builder for updating this Project.
// Note that you need to call Project.Unwrap() before calling this method if this Project
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Project) Update() *ProjectUpdateOne {
	return NewProjectClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Project entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Project) Unwrap() *Project {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Project is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Project) String() string {
	var builder strings.Builder
	builder.WriteString("Project(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("slug=")
	builder.WriteString(_m.Slug)
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(_m.CreatedBy)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("context_text=")
	builder.WriteString(_m.ContextText)
	builder.WriteString(", ")
	builder.WriteString("context_version=")
	builder.WriteString(fmt.Sprintf("%v", _m.ContextVersion))
	builder.WriteString(", ")
	builder.WriteString("context_updated_by=")
	builder.WriteString(_m.ContextUpdatedBy)
	builder.WriteString(", ")
	if v := _m.ContextUpdatedAt; v != nil {
		builder.WriteString("context_updated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// Projects is a parsable slice of Project.
type Projects []*Project
