// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/francogalfre/coop/apps/relay/internal/db/ent/project"
	"github.com/francogalfre/coop/apps/relay/internal/db/ent/projectinvite"
)

// ProjectInviteCreate is the builder for creating a ProjectInvite entity.
type ProjectInviteCreate struct {
	config
	mutation *ProjectInviteMutation
	hooks    []Hook
}

// SetTokenHash sets the "token_hash" field.
func (_c *ProjectInviteCreate) SetTokenHash(v []byte) *ProjectInviteCreate {
	_c.mutation.SetTokenHash(v)
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *ProjectInviteCreate) SetCreatedBy(v string) *ProjectInviteCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ProjectInviteCreate) SetCreatedAt(v time.Time) *ProjectInviteCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ProjectInviteCreate) SetNillableCreatedAt(v *time.Time) *ProjectInviteCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *ProjectInviteCreate) SetExpiresAt(v time.Time) *ProjectInviteCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetRevokedAt sets the "revoked_at" field.
func (_c *ProjectInviteCreate) SetRevokedAt(v time.Time) *ProjectInviteCreate {
	_c.mutation.SetRevokedAt(v)
	return _c
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_c *ProjectInviteCreate) SetNillableRevokedAt(v *time.Time) *ProjectInviteCreate {
	if v != nil {
		_c.SetRevokedAt(*v)
	}
	return _c
}

// SetProjectID sets the "project" edge to the Project entity by ID.
func (_c *ProjectInviteCreate) SetProjectID(id int) *ProjectInviteCreate {
	_c.mutation.SetProjectID(id)
	return _c
}

// SetProject sets the "project" edge to the Project entity.
func (_c *ProjectInviteCreate) SetProject(v *Project) *ProjectInviteCreate {
	return _c.SetProjectID(v.ID)
}

// Mutation returns the ProjectInviteMutation object of the builder.
func (_c *ProjectInviteCreate) Mutation() *ProjectInviteMutation {
	return _c.mutation
}

// Save creates the ProjectInvite in the database.
func (_c *ProjectInviteCreate) Save(ctx context.Context) (*ProjectInvite, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProjectInviteCreate) SaveX(ctx context.Context) *ProjectInvite {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProjectInviteCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProjectInviteCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ProjectInviteCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := projectinvite.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProjectInviteCreate) check() error {
	if _, ok := _c.mutation.TokenHash(); !ok {
		return &ValidationError{Name: "token_hash", err: errors.New(`ent: missing required field "ProjectInvite.token_hash"`)}
	}
	if v, ok := _c.mutation.TokenHash(); ok {
		if err := projectinvite.TokenHashValidator(v); err != nil {
			return &ValidationError{Name: "token_hash", err: fmt.Errorf(`ent: validator failed for field "ProjectInvite.token_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "ProjectInvite.created_by"`)}
	}
	if v, ok := _c.mutation.CreatedBy(); ok {
		if err := projectinvite.CreatedByValidator(v); err != nil {
			return &ValidationError{Name: "created_by", err: fmt.Errorf(`ent: validator failed for field "ProjectInvite.created_by": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ProjectInvite.created_at"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "ProjectInvite.expires_at"`)}
	}
	if len(_c.mutation.ProjectIDs()) == 0 {
		return &ValidationError{Name: "project", err: errors.New(`ent: missing required edge "ProjectInvite.project"`)}
	}
	return nil
}

func (_c *ProjectInviteCreate) sqlSave(ctx context.Context) (*ProjectInvite, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ProjectInviteCreate) createSpec() (*ProjectInvite, *sqlgraph.CreateSpec) {
	var (
		_node = &ProjectInvite{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(projectinvite.Table, sqlgraph.NewFieldSpec(projectinvite.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.TokenHash(); ok {
		_spec.SetField(projectinvite.FieldTokenHash, field.TypeBytes, value)
		_node.TokenHash = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(projectinvite.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(projectinvite.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(projectinvite.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.RevokedAt(); ok {
		_spec.SetField(projectinvite.FieldRevokedAt, field.TypeTime, value)
		_node.RevokedAt = &value
	}
	if nodes := _c.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projectinvite.ProjectTable,
			Columns: []string{projectinvite.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.project_invites = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ProjectInviteCreateBulk is the builder for creating many ProjectInvite entities in bulk.
type ProjectInviteCreateBulk struct {
	config
	err      error
	builders []*ProjectInviteCreate
}

// Save creates the ProjectInvite entities in the database.
func (_c *ProjectInviteCreateBulk) Save(ctx context.Context) ([]*ProjectInvite, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ProjectInvite, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProjectInviteMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProjectInviteCreateBulk) SaveX(ctx context.Context) []*ProjectInvite {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProjectInviteCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProjectInviteCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
