// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/francogalfre/coop/apps/relay/internal/db/ent/predicate"
	"github.com/francogalfre/coop/apps/relay/internal/db/ent/projectnote"
)

// ProjectNoteDelete is the builder for deleting a ProjectNote entity.
type ProjectNoteDelete struct {
	config
	hooks    []Hook
	mutation *ProjectNoteMutation
}

// Where appends a list predicates to the ProjectNoteDelete builder.
func (_d *ProjectNoteDelete) Where(ps ...predicate.ProjectNote) *ProjectNoteDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ProjectNoteDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ProjectNoteDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ProjectNoteDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(projectnote.Table, sqlgraph.NewFieldSpec(projectnote.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ProjectNoteDeleteOne is the builder for deleting a single ProjectNote entity.
type ProjectNoteDeleteOne struct {
	_d *ProjectNoteDelete
}

// Where appends a list predicates to the ProjectNoteDelete builder.
func (_d *ProjectNoteDeleteOne) Where(ps ...predicate.ProjectNote) *ProjectNoteDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ProjectNoteDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{projectnote.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ProjectNoteDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
