// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/francogalfre/coop/apps/relay/internal/db/ent/agent"
	"github.com/francogalfre/coop/apps/relay/internal/db/ent/agentsession"
	"github.com/francogalfre/coop/apps/relay/internal/db/ent/project"
	"github.com/francogalfre/coop/apps/relay/internal/db/ent/projectinvite"
	"github.com/francogalfre/coop/apps/relay/internal/db/ent/projectmember"
	"github.com/francogalfre/coop/apps/relay/internal/db/ent/projectnote"
)

// ProjectCreate is the builder for creating a Project entity.
type ProjectCreate struct {
	config
	mutation *ProjectMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *ProjectCreate) SetName(v string) *ProjectCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetSlug sets the "slug" field.
func (_c *ProjectCreate) SetSlug(v string) *ProjectCreate {
	_c.mutation.SetSlug(v)
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *ProjectCreate) SetCreatedBy(v string) *ProjectCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ProjectCreate) SetCreatedAt(v time.Time) *ProjectCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ProjectCreate) SetNillableCreatedAt(v *time.Time) *ProjectCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetContextText sets the "context_text" field.
func (_c *ProjectCreate) SetContextText(v string) *ProjectCreate {
	_c.mutation.SetContextText(v)
	return _c
}

// SetNillableContextText sets the "context_text" field if the given value is not nil.
func (_c *ProjectCreate) SetNillableContextText(v *string) *ProjectCreate {
	if v != nil {
		_c.SetContextText(*v)
	}
	return _c
}

// SetContextVersion sets the "context_version" field.
func (_c *ProjectCreate) SetContextVersion(v int) *ProjectCreate {
	_c.mutation.SetContextVersion(v)
	return _c
}

// SetNillableContextVersion sets the "context_version" field if the given value is not nil.
func (_c *ProjectCreate) SetNillableContextVersion(v *int) *ProjectCreate {
	if v != nil {
		_c.SetContextVersion(*v)
	}
	return _c
}

// SetContextUpdatedBy sets the "context_updated_by" field.
func (_c *ProjectCreate) SetContextUpdatedBy(v string) *ProjectCreate {
	_c.mutation.SetContextUpdatedBy(v)
	return _c
}

// SetNillableContextUpdatedBy sets the "context_updated_by" field if the given value is not nil.
func (_c *ProjectCreate) SetNillableContextUpdatedBy(v *string) *ProjectCreate {
	if v != nil {
		_c.SetContextUpdatedBy(*v)
	}
	return _c
}

// SetContextUpdatedAt sets the "context_updated_at" field.
func (_c *ProjectCreate) SetContextUpdatedAt(v time.Time) *ProjectCreate {
	_c.mutation.SetContextUpdatedAt(v)
	return _c
}

// SetNillableContextUpdatedAt sets the "context_updated_at" field if the given value is not nil.
func (_c *ProjectCreate) SetNillableContextUpdatedAt(v *time.Time) *ProjectCreate {
	if v != nil {
		_c.SetContextUpdatedAt(*v)
	}
	return _c
}

// AddMemberIDs adds the "members" edge to the ProjectMember entity by IDs.
func (_c *ProjectCreate) AddMemberIDs(ids ...int) *ProjectCreate {
	_c.mutation.AddMemberIDs(ids...)
	return _c
}

// AddMembers adds the "members" edges to the ProjectMember entity.
func (_c *ProjectCreate) AddMembers(v ...*ProjectMember) *ProjectCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMemberIDs(ids...)
}

// AddInviteIDs adds the "invites" edge to the ProjectInvite entity by IDs.
func (_c *ProjectCreate) AddInviteIDs(ids ...int) *ProjectCreate {
	_c.mutation.AddInviteIDs(ids...)
	return _c
}

// AddInvites adds the "invites" edges to the ProjectInvite entity.
func (_c *ProjectCreate) AddInvites(v ...*ProjectInvite) *ProjectCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddInviteIDs(ids...)
}

// AddSessionIDs adds the "sessions" edge to the AgentSession entity by IDs.
func (_c *ProjectCreate) AddSessionIDs(ids ...string) *ProjectCreate {
	_c.mutation.AddSessionIDs(ids...)
	return _c
}

// AddSessions adds the "sessions" edges to the AgentSession entity.
func (_c *ProjectCreate) AddSessions(v ...*AgentSession) *ProjectCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSessionIDs(ids...)
}

// AddAgentIDs adds the "agents" edge to the Agent entity by IDs.
func (_c *ProjectCreate) AddAgentIDs(ids ...string) *ProjectCreate {
	_c.mutation.AddAgentIDs(ids...)
	return _c
}

// AddAgents adds the "agents" edges to the Agent entity.
func (_c *ProjectCreate) AddAgents(v ...*Agent) *ProjectCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAgentIDs(ids...)
}

// AddNoteIDs adds the "notes" edge to the ProjectNote entity by IDs.
func (_c *ProjectCreate) AddNoteIDs(ids ...string) *ProjectCreate {
	_c.mutation.AddNoteIDs(ids...)
	return _c
}

// AddNotes adds the "notes" edges to the ProjectNote entity.
func (_c *ProjectCreate) AddNotes(v ...*ProjectNote) *ProjectCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddNoteIDs(ids...)
}

// Mutation returns the ProjectMutation object of the builder.
func (_c *ProjectCreate) Mutation() *ProjectMutation {
	return _c.mutation
}

// Save creates the Project in the database.
func (_c *ProjectCreate) Save(ctx context.Context) (*Project, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProjectCreate) SaveX(ctx context.Context) *Project {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProjectCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProjectCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ProjectCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := project.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ContextText(); !ok {
		v := project.DefaultContextText
		_c.mutation.SetContextText(v)
	}
	if _, ok := _c.mutation.ContextVersion(); !ok {
		v := project.DefaultContextVersion
		_c.mutation.SetContextVersion(v)
	}
	if _, ok := _c.mutation.ContextUpdatedBy(); !ok {
		v := project.DefaultContextUpdatedBy
		_c.mutation.SetContextUpdatedBy(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProjectCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Project.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := project.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Project.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Slug(); !ok {
		return &ValidationError{Name: "slug", err: errors.New(`ent: missing required field "Project.slug"`)}
	}
	if v, ok := _c.mutation.Slug(); ok {
		if err := project.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "Project.slug": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "Project.created_by"`)}
	}
	if v, ok := _c.mutation.CreatedBy(); ok {
		if err := project.CreatedByValidator(v); err != nil {
			return &ValidationError{Name: "created_by", err: fmt.Errorf(`ent: validator failed for field "Project.created_by": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Project.created_at"`)}
	}
	if _, ok := _c.mutation.ContextText(); !ok {
		return &ValidationError{Name: "context_text", err: errors.New(`ent: missing required field "Project.context_text"`)}
	}
	if _, ok := _c.mutation.ContextVersion(); !ok {
		return &ValidationError{Name: "context_version", err: errors.New(`ent: missing required field "Project.context_version"`)}
	}
	if v, ok := _c.mutation.ContextVersion(); ok {
		if err := project.ContextVersionValidator(v); err != nil {
			return &ValidationError{Name: "context_version", err: fmt.Errorf(`ent: validator failed for field "Project.context_version": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ContextUpdatedBy(); !ok {
		return &ValidationError{Name: "context_updated_by", err: errors.New(`ent: missing required field "Project.context_updated_by"`)}
	}
	return nil
}

func (_c *ProjectCreate) sqlSave(ctx context.Context) (*Project, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ProjectCreate) createSpec() (*Project, *sqlgraph.CreateSpec) {
	var (
		_node = &Project{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(project.Table, sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(project.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Slug(); ok {
		_spec.SetField(project.FieldSlug, field.TypeString, value)
		_node.Slug = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(project.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(project.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.ContextText(); ok {
		_spec.SetField(project.FieldContextText, field.TypeString, value)
		_node.ContextText = value
	}
	if value, ok := _c.mutation.ContextVersion(); ok {
		_spec.SetField(project.FieldContextVersion, field.TypeInt, value)
		_node.ContextVersion = value
	}
	if value, ok := _c.mutation.ContextUpdatedBy(); ok {
		_spec.SetField(project.FieldContextUpdatedBy, field.TypeString, value)
		_node.ContextUpdatedBy = value
	}
	if value, ok := _c.mutation.ContextUpdatedAt(); ok {
		_spec.SetField(project.FieldContextUpdatedAt, field.TypeTime, value)
		_node.ContextUpdatedAt = &value
	}
	if nodes := _c.mutation.MembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.MembersTable,
			Columns: []string{project.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(projectmember.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.InvitesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.InvitesTable,
			Columns: []string{project.InvitesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(projectinvite.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SessionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.SessionsTable,
			Columns: []string{project.SessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agentsession.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AgentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.AgentsTable,
			Columns: []string{project.AgentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.NotesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.NotesTable,
			Columns: []string{project.NotesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(projectnote.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ProjectCreateBulk is the builder for creating many Project entities in bulk.
type ProjectCreateBulk struct {
	config
	err      error
	builders []*ProjectCreate
}

// Save creates the Project entities in the database.
func (_c *ProjectCreateBulk) Save(ctx context.Context) ([]*Project, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Project, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProjectMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProjectCreateBulk) SaveX(ctx context.Context) []*Project {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProjectCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProjectCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
