// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/francogalfre/coop/apps/relay/internal/db/ent/project"
	"github.com/francogalfre/coop/apps/relay/internal/db/ent/projectinvite"
)

// ProjectInvite is the model entity for the ProjectInvite schema.
type ProjectInvite struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// TokenHash holds the value of the "token_hash" field.
	TokenHash []byte `json:"token_hash,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy string `json:"created_by,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// RevokedAt holds the value of the "revoked_at" field.
	RevokedAt *time.Time `json:"revoked_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ProjectInviteQuery when eager-loading is set.
	Edges           ProjectInviteEdges `json:"edges"`
	project_invites *int
	selectValues    sql.SelectValues
}

// ProjectInviteEdges holds the relations/edges for other nodes in the graph.
type ProjectInviteEdges struct {
	// Project holds the value of the project edge.
	Project *Project `json:"project,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ProjectOrErr returns the Project value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ProjectInviteEdges) ProjectOrErr() (*Project, error) {
	if e.Project != nil {
		return e.Project, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: project.Label}
	}
	return nil, &NotLoadedError{edge: "project"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ProjectInvite) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case projectinvite.FieldTokenHash:
			values[i] = new([]byte)
		case projectinvite.FieldID:
			values[i] = new(sql.NullInt64)
		case projectinvite.FieldCreatedBy:
			values[i] = new(sql.NullString)
		case projectinvite.FieldCreatedAt, projectinvite.FieldExpiresAt, projectinvite.FieldRevokedAt:
			values[i] = new(sql.NullTime)
		case projectinvite.ForeignKeys[0]: // project_invites
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ProjectInvite fields.
func (_m *ProjectInvite) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case projectinvite.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case projectinvite.FieldTokenHash:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field token_hash", values[i])
			} else if value != nil {
				_m.TokenHash = *value
			}
		case projectinvite.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = value.String
			}
		case projectinvite.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case projectinvite.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case projectinvite.FieldRevokedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field revoked_at", values[i])
			} else if value.Valid {
				_m.RevokedAt = new(time.Time)
				*_m.RevokedAt = value.Time
			}
		case projectinvite.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field project_invites", value)
			} else if value.Valid {
				_m.project_invites = new(int)
				*_m.project_invites = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ProjectInvite.
// This includes values selected through modifiers, order, etc.
func (_m *ProjectInvite) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProject queries the "project" edge of the ProjectInvite entity.
func (_m *ProjectInvite) QueryProject() *ProjectQuery {
	return NewProjectInviteClient(_m.config).QueryProject(_m)
}

// Update returns a builder for updating this ProjectInvite.
// Note that you need to call ProjectInvite.Unwrap() before calling this method if this ProjectInvite
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ProjectInvite) Update() *ProjectInviteUpdateOne {
	return NewProjectInviteClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ProjectInvite entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ProjectInvite) Unwrap() *ProjectInvite {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ProjectInvite is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ProjectInvite) String() string {
	var builder strings.Builder
	builder.WriteString("ProjectInvite(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("token_hash=")
	builder.WriteString(fmt.Sprintf("%v", _m.TokenHash))
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(_m.CreatedBy)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.RevokedAt; v != nil {
		builder.WriteString("revoked_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// ProjectInvites is a parsable slice of ProjectInvite.
type ProjectInvites []*ProjectInvite
