// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/francogalfre/coop/apps/relay/internal/db/ent/agentsession"
	"github.com/francogalfre/coop/apps/relay/internal/db/ent/clicredential"
	"github.com/francogalfre/coop/apps/relay/internal/db/ent/event"
	"github.com/francogalfre/coop/apps/relay/internal/db/ent/project"
	"github.com/francogalfre/coop/apps/relay/internal/db/ent/projectinvite"
	"github.com/francogalfre/coop/apps/relay/internal/db/ent/projectmember"
	"github.com/francogalfre/coop/apps/relay/internal/db/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	agentsessionFields := schema.AgentSession{}.Fields()
	_ = agentsessionFields
	// agentsessionDescOwnerID is the schema descriptor for owner_id field.
	agentsessionDescOwnerID := agentsessionFields[1].Descriptor()
	// agentsession.OwnerIDValidator is a validator for the "owner_id" field. It is called by the builders before save.
	agentsession.OwnerIDValidator = agentsessionDescOwnerID.Validators[0].(func(string) error)
	// agentsessionDescRepo is the schema descriptor for repo field.
	agentsessionDescRepo := agentsessionFields[2].Descriptor()
	// agentsession.DefaultRepo holds the default value on creation for the repo field.
	agentsession.DefaultRepo = agentsessionDescRepo.Default.(string)
	// agentsessionDescCwd is the schema descriptor for cwd field.
	agentsessionDescCwd := agentsessionFields[3].Descriptor()
	// agentsession.DefaultCwd holds the default value on creation for the cwd field.
	agentsession.DefaultCwd = agentsessionDescCwd.Default.(string)
	// agentsessionDescHarness is the schema descriptor for harness field.
	agentsessionDescHarness := agentsessionFields[4].Descriptor()
	// agentsession.DefaultHarness holds the default value on creation for the harness field.
	agentsession.DefaultHarness = agentsessionDescHarness.Default.(string)
	// agentsessionDescStatus is the schema descriptor for status field.
	agentsessionDescStatus := agentsessionFields[5].Descriptor()
	// agentsession.DefaultStatus holds the default value on creation for the status field.
	agentsession.DefaultStatus = agentsessionDescStatus.Default.(string)
	// agentsessionDescNextSeq is the schema descriptor for next_seq field.
	agentsessionDescNextSeq := agentsessionFields[6].Descriptor()
	// agentsession.DefaultNextSeq holds the default value on creation for the next_seq field.
	agentsession.DefaultNextSeq = agentsessionDescNextSeq.Default.(int)
	// agentsession.NextSeqValidator is a validator for the "next_seq" field. It is called by the builders before save.
	agentsession.NextSeqValidator = agentsessionDescNextSeq.Validators[0].(func(int) error)
	// agentsessionDescID is the schema descriptor for id field.
	agentsessionDescID := agentsessionFields[0].Descriptor()
	// agentsession.IDValidator is a validator for the "id" field. It is called by the builders before save.
	agentsession.IDValidator = agentsessionDescID.Validators[0].(func(string) error)
	clicredentialFields := schema.CliCredential{}.Fields()
	_ = clicredentialFields
	// clicredentialDescUserID is the schema descriptor for user_id field.
	clicredentialDescUserID := clicredentialFields[0].Descriptor()
	// clicredential.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	clicredential.UserIDValidator = clicredentialDescUserID.Validators[0].(func(string) error)
	// clicredentialDescTokenHash is the schema descriptor for token_hash field.
	clicredentialDescTokenHash := clicredentialFields[1].Descriptor()
	// clicredential.TokenHashValidator is a validator for the "token_hash" field. It is called by the builders before save.
	clicredential.TokenHashValidator = clicredentialDescTokenHash.Validators[0].(func([]byte) error)
	// clicredentialDescCreatedAt is the schema descriptor for created_at field.
	clicredentialDescCreatedAt := clicredentialFields[2].Descriptor()
	// clicredential.DefaultCreatedAt holds the default value on creation for the created_at field.
	clicredential.DefaultCreatedAt = clicredentialDescCreatedAt.Default.(func() time.Time)
	eventFields := schema.Event{}.Fields()
	_ = eventFields
	// eventDescSeq is the schema descriptor for seq field.
	eventDescSeq := eventFields[0].Descriptor()
	// event.SeqValidator is a validator for the "seq" field. It is called by the builders before save.
	event.SeqValidator = eventDescSeq.Validators[0].(func(int) error)
	// eventDescData is the schema descriptor for data field.
	eventDescData := eventFields[1].Descriptor()
	// event.DataValidator is a validator for the "data" field. It is called by the builders before save.
	event.DataValidator = eventDescData.Validators[0].(func([]byte) error)
	// eventDescCreatedAt is the schema descriptor for created_at field.
	eventDescCreatedAt := eventFields[2].Descriptor()
	// event.DefaultCreatedAt holds the default value on creation for the created_at field.
	event.DefaultCreatedAt = eventDescCreatedAt.Default.(func() time.Time)
	projectFields := schema.Project{}.Fields()
	_ = projectFields
	// projectDescName is the schema descriptor for name field.
	projectDescName := projectFields[0].Descriptor()
	// project.NameValidator is a validator for the "name" field. It is called by the builders before save.
	project.NameValidator = projectDescName.Validators[0].(func(string) error)
	// projectDescSlug is the schema descriptor for slug field.
	projectDescSlug := projectFields[1].Descriptor()
	// project.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	project.SlugValidator = projectDescSlug.Validators[0].(func(string) error)
	// projectDescCreatedBy is the schema descriptor for created_by field.
	projectDescCreatedBy := projectFields[2].Descriptor()
	// project.CreatedByValidator is a validator for the "created_by" field. It is called by the builders before save.
	project.CreatedByValidator = projectDescCreatedBy.Validators[0].(func(string) error)
	// projectDescCreatedAt is the schema descriptor for created_at field.
	projectDescCreatedAt := projectFields[3].Descriptor()
	// project.DefaultCreatedAt holds the default value on creation for the created_at field.
	project.DefaultCreatedAt = projectDescCreatedAt.Default.(func() time.Time)
	projectinviteFields := schema.ProjectInvite{}.Fields()
	_ = projectinviteFields
	// projectinviteDescTokenHash is the schema descriptor for token_hash field.
	projectinviteDescTokenHash := projectinviteFields[0].Descriptor()
	// projectinvite.TokenHashValidator is a validator for the "token_hash" field. It is called by the builders before save.
	projectinvite.TokenHashValidator = projectinviteDescTokenHash.Validators[0].(func([]byte) error)
	// projectinviteDescCreatedBy is the schema descriptor for created_by field.
	projectinviteDescCreatedBy := projectinviteFields[1].Descriptor()
	// projectinvite.CreatedByValidator is a validator for the "created_by" field. It is called by the builders before save.
	projectinvite.CreatedByValidator = projectinviteDescCreatedBy.Validators[0].(func(string) error)
	// projectinviteDescCreatedAt is the schema descriptor for created_at field.
	projectinviteDescCreatedAt := projectinviteFields[2].Descriptor()
	// projectinvite.DefaultCreatedAt holds the default value on creation for the created_at field.
	projectinvite.DefaultCreatedAt = projectinviteDescCreatedAt.Default.(func() time.Time)
	projectmemberFields := schema.ProjectMember{}.Fields()
	_ = projectmemberFields
	// projectmemberDescUserID is the schema descriptor for user_id field.
	projectmemberDescUserID := projectmemberFields[0].Descriptor()
	// projectmember.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	projectmember.UserIDValidator = projectmemberDescUserID.Validators[0].(func(string) error)
	// projectmemberDescRole is the schema descriptor for role field.
	projectmemberDescRole := projectmemberFields[1].Descriptor()
	// projectmember.RoleValidator is a validator for the "role" field. It is called by the builders before save.
	projectmember.RoleValidator = projectmemberDescRole.Validators[0].(func(string) error)
	// projectmemberDescJoinedAt is the schema descriptor for joined_at field.
	projectmemberDescJoinedAt := projectmemberFields[2].Descriptor()
	// projectmember.DefaultJoinedAt holds the default value on creation for the joined_at field.
	projectmember.DefaultJoinedAt = projectmemberDescJoinedAt.Default.(func() time.Time)
}
