// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/francogalfre/coop/apps/relay/internal/db/ent/agent"
	"github.com/francogalfre/coop/apps/relay/internal/db/ent/agentsession"
	"github.com/francogalfre/coop/apps/relay/internal/db/ent/clicredential"
	"github.com/francogalfre/coop/apps/relay/internal/db/ent/event"
	"github.com/francogalfre/coop/apps/relay/internal/db/ent/project"
	"github.com/francogalfre/coop/apps/relay/internal/db/ent/projectinvite"
	"github.com/francogalfre/coop/apps/relay/internal/db/ent/projectmember"
	"github.com/francogalfre/coop/apps/relay/internal/db/ent/schema"
	"github.com/francogalfre/coop/apps/relay/internal/db/ent/steerrequest"
	"github.com/francogalfre/coop/apps/relay/internal/db/ent/takeover"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	agentFields := schema.Agent{}.Fields()
	_ = agentFields
	// agentDescName is the schema descriptor for name field.
	agentDescName := agentFields[1].Descriptor()
	// agent.NameValidator is a validator for the "name" field. It is called by the builders before save.
	agent.NameValidator = agentDescName.Validators[0].(func(string) error)
	// agentDescDisplayName is the schema descriptor for display_name field.
	agentDescDisplayName := agentFields[2].Descriptor()
	// agent.DefaultDisplayName holds the default value on creation for the display_name field.
	agent.DefaultDisplayName = agentDescDisplayName.Default.(string)
	// agentDescCreatedBy is the schema descriptor for created_by field.
	agentDescCreatedBy := agentFields[3].Descriptor()
	// agent.CreatedByValidator is a validator for the "created_by" field. It is called by the builders before save.
	agent.CreatedByValidator = agentDescCreatedBy.Validators[0].(func(string) error)
	// agentDescCreatedAt is the schema descriptor for created_at field.
	agentDescCreatedAt := agentFields[4].Descriptor()
	// agent.DefaultCreatedAt holds the default value on creation for the created_at field.
	agent.DefaultCreatedAt = agentDescCreatedAt.Default.(func() time.Time)
	// agentDescID is the schema descriptor for id field.
	agentDescID := agentFields[0].Descriptor()
	// agent.IDValidator is a validator for the "id" field. It is called by the builders before save.
	agent.IDValidator = agentDescID.Validators[0].(func(string) error)
	agentsessionFields := schema.AgentSession{}.Fields()
	_ = agentsessionFields
	// agentsessionDescOwnerID is the schema descriptor for owner_id field.
	agentsessionDescOwnerID := agentsessionFields[1].Descriptor()
	// agentsession.OwnerIDValidator is a validator for the "owner_id" field. It is called by the builders before save.
	agentsession.OwnerIDValidator = agentsessionDescOwnerID.Validators[0].(func(string) error)
	// agentsessionDescRepo is the schema descriptor for repo field.
	agentsessionDescRepo := agentsessionFields[2].Descriptor()
	// agentsession.DefaultRepo holds the default value on creation for the repo field.
	agentsession.DefaultRepo = agentsessionDescRepo.Default.(string)
	// agentsessionDescCwd is the schema descriptor for cwd field.
	agentsessionDescCwd := agentsessionFields[3].Descriptor()
	// agentsession.DefaultCwd holds the default value on creation for the cwd field.
	agentsession.DefaultCwd = agentsessionDescCwd.Default.(string)
	// agentsessionDescHarness is the schema descriptor for harness field.
	agentsessionDescHarness := agentsessionFields[4].Descriptor()
	// agentsession.DefaultHarness holds the default value on creation for the harness field.
	agentsession.DefaultHarness = agentsessionDescHarness.Default.(string)
	// agentsessionDescStatus is the schema descriptor for status field.
	agentsessionDescStatus := agentsessionFields[5].Descriptor()
	// agentsession.DefaultStatus holds the default value on creation for the status field.
	agentsession.DefaultStatus = agentsessionDescStatus.Default.(string)
	// agentsessionDescMode is the schema descriptor for mode field.
	agentsessionDescMode := agentsessionFields[6].Descriptor()
	// agentsession.DefaultMode holds the default value on creation for the mode field.
	agentsession.DefaultMode = agentsessionDescMode.Default.(string)
	// agentsessionDescNextSeq is the schema descriptor for next_seq field.
	agentsessionDescNextSeq := agentsessionFields[7].Descriptor()
	// agentsession.DefaultNextSeq holds the default value on creation for the next_seq field.
	agentsession.DefaultNextSeq = agentsessionDescNextSeq.Default.(int)
	// agentsession.NextSeqValidator is a validator for the "next_seq" field. It is called by the builders before save.
	agentsession.NextSeqValidator = agentsessionDescNextSeq.Validators[0].(func(int) error)
	// agentsessionDescID is the schema descriptor for id field.
	agentsessionDescID := agentsessionFields[0].Descriptor()
	// agentsession.IDValidator is a validator for the "id" field. It is called by the builders before save.
	agentsession.IDValidator = agentsessionDescID.Validators[0].(func(string) error)
	clicredentialFields := schema.CliCredential{}.Fields()
	_ = clicredentialFields
	// clicredentialDescUserID is the schema descriptor for user_id field.
	clicredentialDescUserID := clicredentialFields[0].Descriptor()
	// clicredential.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	clicredential.UserIDValidator = clicredentialDescUserID.Validators[0].(func(string) error)
	// clicredentialDescDisplayName is the schema descriptor for display_name field.
	clicredentialDescDisplayName := clicredentialFields[1].Descriptor()
	// clicredential.DefaultDisplayName holds the default value on creation for the display_name field.
	clicredential.DefaultDisplayName = clicredentialDescDisplayName.Default.(string)
	// clicredentialDescTokenHash is the schema descriptor for token_hash field.
	clicredentialDescTokenHash := clicredentialFields[2].Descriptor()
	// clicredential.TokenHashValidator is a validator for the "token_hash" field. It is called by the builders before save.
	clicredential.TokenHashValidator = clicredentialDescTokenHash.Validators[0].(func([]byte) error)
	// clicredentialDescCreatedAt is the schema descriptor for created_at field.
	clicredentialDescCreatedAt := clicredentialFields[3].Descriptor()
	// clicredential.DefaultCreatedAt holds the default value on creation for the created_at field.
	clicredential.DefaultCreatedAt = clicredentialDescCreatedAt.Default.(func() time.Time)
	eventFields := schema.Event{}.Fields()
	_ = eventFields
	// eventDescSeq is the schema descriptor for seq field.
	eventDescSeq := eventFields[0].Descriptor()
	// event.SeqValidator is a validator for the "seq" field. It is called by the builders before save.
	event.SeqValidator = eventDescSeq.Validators[0].(func(int) error)
	// eventDescData is the schema descriptor for data field.
	eventDescData := eventFields[1].Descriptor()
	// event.DataValidator is a validator for the "data" field. It is called by the builders before save.
	event.DataValidator = eventDescData.Validators[0].(func([]byte) error)
	// eventDescCreatedAt is the schema descriptor for created_at field.
	eventDescCreatedAt := eventFields[2].Descriptor()
	// event.DefaultCreatedAt holds the default value on creation for the created_at field.
	event.DefaultCreatedAt = eventDescCreatedAt.Default.(func() time.Time)
	projectFields := schema.Project{}.Fields()
	_ = projectFields
	// projectDescName is the schema descriptor for name field.
	projectDescName := projectFields[0].Descriptor()
	// project.NameValidator is a validator for the "name" field. It is called by the builders before save.
	project.NameValidator = projectDescName.Validators[0].(func(string) error)
	// projectDescSlug is the schema descriptor for slug field.
	projectDescSlug := projectFields[1].Descriptor()
	// project.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	project.SlugValidator = projectDescSlug.Validators[0].(func(string) error)
	// projectDescCreatedBy is the schema descriptor for created_by field.
	projectDescCreatedBy := projectFields[2].Descriptor()
	// project.CreatedByValidator is a validator for the "created_by" field. It is called by the builders before save.
	project.CreatedByValidator = projectDescCreatedBy.Validators[0].(func(string) error)
	// projectDescCreatedAt is the schema descriptor for created_at field.
	projectDescCreatedAt := projectFields[3].Descriptor()
	// project.DefaultCreatedAt holds the default value on creation for the created_at field.
	project.DefaultCreatedAt = projectDescCreatedAt.Default.(func() time.Time)
	projectinviteFields := schema.ProjectInvite{}.Fields()
	_ = projectinviteFields
	// projectinviteDescTokenHash is the schema descriptor for token_hash field.
	projectinviteDescTokenHash := projectinviteFields[0].Descriptor()
	// projectinvite.TokenHashValidator is a validator for the "token_hash" field. It is called by the builders before save.
	projectinvite.TokenHashValidator = projectinviteDescTokenHash.Validators[0].(func([]byte) error)
	// projectinviteDescCreatedBy is the schema descriptor for created_by field.
	projectinviteDescCreatedBy := projectinviteFields[1].Descriptor()
	// projectinvite.CreatedByValidator is a validator for the "created_by" field. It is called by the builders before save.
	projectinvite.CreatedByValidator = projectinviteDescCreatedBy.Validators[0].(func(string) error)
	// projectinviteDescCreatedAt is the schema descriptor for created_at field.
	projectinviteDescCreatedAt := projectinviteFields[2].Descriptor()
	// projectinvite.DefaultCreatedAt holds the default value on creation for the created_at field.
	projectinvite.DefaultCreatedAt = projectinviteDescCreatedAt.Default.(func() time.Time)
	projectmemberFields := schema.ProjectMember{}.Fields()
	_ = projectmemberFields
	// projectmemberDescUserID is the schema descriptor for user_id field.
	projectmemberDescUserID := projectmemberFields[0].Descriptor()
	// projectmember.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	projectmember.UserIDValidator = projectmemberDescUserID.Validators[0].(func(string) error)
	// projectmemberDescRole is the schema descriptor for role field.
	projectmemberDescRole := projectmemberFields[1].Descriptor()
	// projectmember.RoleValidator is a validator for the "role" field. It is called by the builders before save.
	projectmember.RoleValidator = projectmemberDescRole.Validators[0].(func(string) error)
	// projectmemberDescJoinedAt is the schema descriptor for joined_at field.
	projectmemberDescJoinedAt := projectmemberFields[2].Descriptor()
	// projectmember.DefaultJoinedAt holds the default value on creation for the joined_at field.
	projectmember.DefaultJoinedAt = projectmemberDescJoinedAt.Default.(func() time.Time)
	steerrequestFields := schema.SteerRequest{}.Fields()
	_ = steerrequestFields
	// steerrequestDescActorID is the schema descriptor for actor_id field.
	steerrequestDescActorID := steerrequestFields[1].Descriptor()
	// steerrequest.ActorIDValidator is a validator for the "actor_id" field. It is called by the builders before save.
	steerrequest.ActorIDValidator = steerrequestDescActorID.Validators[0].(func(string) error)
	// steerrequestDescActorDisplayName is the schema descriptor for actor_display_name field.
	steerrequestDescActorDisplayName := steerrequestFields[2].Descriptor()
	// steerrequest.DefaultActorDisplayName holds the default value on creation for the actor_display_name field.
	steerrequest.DefaultActorDisplayName = steerrequestDescActorDisplayName.Default.(string)
	// steerrequestDescActorAvatarURL is the schema descriptor for actor_avatar_url field.
	steerrequestDescActorAvatarURL := steerrequestFields[3].Descriptor()
	// steerrequest.DefaultActorAvatarURL holds the default value on creation for the actor_avatar_url field.
	steerrequest.DefaultActorAvatarURL = steerrequestDescActorAvatarURL.Default.(string)
	// steerrequestDescText is the schema descriptor for text field.
	steerrequestDescText := steerrequestFields[4].Descriptor()
	// steerrequest.TextValidator is a validator for the "text" field. It is called by the builders before save.
	steerrequest.TextValidator = steerrequestDescText.Validators[0].(func(string) error)
	// steerrequestDescCreatedAt is the schema descriptor for created_at field.
	steerrequestDescCreatedAt := steerrequestFields[5].Descriptor()
	// steerrequest.DefaultCreatedAt holds the default value on creation for the created_at field.
	steerrequest.DefaultCreatedAt = steerrequestDescCreatedAt.Default.(func() time.Time)
	// steerrequestDescID is the schema descriptor for id field.
	steerrequestDescID := steerrequestFields[0].Descriptor()
	// steerrequest.IDValidator is a validator for the "id" field. It is called by the builders before save.
	steerrequest.IDValidator = steerrequestDescID.Validators[0].(func(string) error)
	takeoverFields := schema.Takeover{}.Fields()
	_ = takeoverFields
	// takeoverDescActorID is the schema descriptor for actor_id field.
	takeoverDescActorID := takeoverFields[1].Descriptor()
	// takeover.ActorIDValidator is a validator for the "actor_id" field. It is called by the builders before save.
	takeover.ActorIDValidator = takeoverDescActorID.Validators[0].(func(string) error)
	// takeoverDescActorDisplayName is the schema descriptor for actor_display_name field.
	takeoverDescActorDisplayName := takeoverFields[2].Descriptor()
	// takeover.DefaultActorDisplayName holds the default value on creation for the actor_display_name field.
	takeover.DefaultActorDisplayName = takeoverDescActorDisplayName.Default.(string)
	// takeoverDescCreatedAt is the schema descriptor for created_at field.
	takeoverDescCreatedAt := takeoverFields[3].Descriptor()
	// takeover.DefaultCreatedAt holds the default value on creation for the created_at field.
	takeover.DefaultCreatedAt = takeoverDescCreatedAt.Default.(func() time.Time)
	// takeoverDescID is the schema descriptor for id field.
	takeoverDescID := takeoverFields[0].Descriptor()
	// takeover.IDValidator is a validator for the "id" field. It is called by the builders before save.
	takeover.IDValidator = takeoverDescID.Validators[0].(func(string) error)
}
