// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/francogalfre/coop/apps/relay/internal/db/ent/agentsession"
	"github.com/francogalfre/coop/apps/relay/internal/db/ent/steerrequest"
)

// SteerRequestCreate is the builder for creating a SteerRequest entity.
type SteerRequestCreate struct {
	config
	mutation *SteerRequestMutation
	hooks    []Hook
}

// SetActorID sets the "actor_id" field.
func (_c *SteerRequestCreate) SetActorID(v string) *SteerRequestCreate {
	_c.mutation.SetActorID(v)
	return _c
}

// SetActorDisplayName sets the "actor_display_name" field.
func (_c *SteerRequestCreate) SetActorDisplayName(v string) *SteerRequestCreate {
	_c.mutation.SetActorDisplayName(v)
	return _c
}

// SetNillableActorDisplayName sets the "actor_display_name" field if the given value is not nil.
func (_c *SteerRequestCreate) SetNillableActorDisplayName(v *string) *SteerRequestCreate {
	if v != nil {
		_c.SetActorDisplayName(*v)
	}
	return _c
}

// SetActorAvatarURL sets the "actor_avatar_url" field.
func (_c *SteerRequestCreate) SetActorAvatarURL(v string) *SteerRequestCreate {
	_c.mutation.SetActorAvatarURL(v)
	return _c
}

// SetNillableActorAvatarURL sets the "actor_avatar_url" field if the given value is not nil.
func (_c *SteerRequestCreate) SetNillableActorAvatarURL(v *string) *SteerRequestCreate {
	if v != nil {
		_c.SetActorAvatarURL(*v)
	}
	return _c
}

// SetText sets the "text" field.
func (_c *SteerRequestCreate) SetText(v string) *SteerRequestCreate {
	_c.mutation.SetText(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SteerRequestCreate) SetCreatedAt(v time.Time) *SteerRequestCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SteerRequestCreate) SetNillableCreatedAt(v *time.Time) *SteerRequestCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SteerRequestCreate) SetID(v string) *SteerRequestCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetSessionID sets the "session" edge to the AgentSession entity by ID.
func (_c *SteerRequestCreate) SetSessionID(id string) *SteerRequestCreate {
	_c.mutation.SetSessionID(id)
	return _c
}

// SetSession sets the "session" edge to the AgentSession entity.
func (_c *SteerRequestCreate) SetSession(v *AgentSession) *SteerRequestCreate {
	return _c.SetSessionID(v.ID)
}

// Mutation returns the SteerRequestMutation object of the builder.
func (_c *SteerRequestCreate) Mutation() *SteerRequestMutation {
	return _c.mutation
}

// Save creates the SteerRequest in the database.
func (_c *SteerRequestCreate) Save(ctx context.Context) (*SteerRequest, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SteerRequestCreate) SaveX(ctx context.Context) *SteerRequest {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SteerRequestCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SteerRequestCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SteerRequestCreate) defaults() {
	if _, ok := _c.mutation.ActorDisplayName(); !ok {
		v := steerrequest.DefaultActorDisplayName
		_c.mutation.SetActorDisplayName(v)
	}
	if _, ok := _c.mutation.ActorAvatarURL(); !ok {
		v := steerrequest.DefaultActorAvatarURL
		_c.mutation.SetActorAvatarURL(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := steerrequest.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SteerRequestCreate) check() error {
	if _, ok := _c.mutation.ActorID(); !ok {
		return &ValidationError{Name: "actor_id", err: errors.New(`ent: missing required field "SteerRequest.actor_id"`)}
	}
	if v, ok := _c.mutation.ActorID(); ok {
		if err := steerrequest.ActorIDValidator(v); err != nil {
			return &ValidationError{Name: "actor_id", err: fmt.Errorf(`ent: validator failed for field "SteerRequest.actor_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ActorDisplayName(); !ok {
		return &ValidationError{Name: "actor_display_name", err: errors.New(`ent: missing required field "SteerRequest.actor_display_name"`)}
	}
	if _, ok := _c.mutation.ActorAvatarURL(); !ok {
		return &ValidationError{Name: "actor_avatar_url", err: errors.New(`ent: missing required field "SteerRequest.actor_avatar_url"`)}
	}
	if _, ok := _c.mutation.Text(); !ok {
		return &ValidationError{Name: "text", err: errors.New(`ent: missing required field "SteerRequest.text"`)}
	}
	if v, ok := _c.mutation.Text(); ok {
		if err := steerrequest.TextValidator(v); err != nil {
			return &ValidationError{Name: "text", err: fmt.Errorf(`ent: validator failed for field "SteerRequest.text": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SteerRequest.created_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := steerrequest.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "SteerRequest.id": %w`, err)}
		}
	}
	if len(_c.mutation.SessionIDs()) == 0 {
		return &ValidationError{Name: "session", err: errors.New(`ent: missing required edge "SteerRequest.session"`)}
	}
	return nil
}

func (_c *SteerRequestCreate) sqlSave(ctx context.Context) (*SteerRequest, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected SteerRequest.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SteerRequestCreate) createSpec() (*SteerRequest, *sqlgraph.CreateSpec) {
	var (
		_node = &SteerRequest{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(steerrequest.Table, sqlgraph.NewFieldSpec(steerrequest.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.ActorID(); ok {
		_spec.SetField(steerrequest.FieldActorID, field.TypeString, value)
		_node.ActorID = value
	}
	if value, ok := _c.mutation.ActorDisplayName(); ok {
		_spec.SetField(steerrequest.FieldActorDisplayName, field.TypeString, value)
		_node.ActorDisplayName = value
	}
	if value, ok := _c.mutation.ActorAvatarURL(); ok {
		_spec.SetField(steerrequest.FieldActorAvatarURL, field.TypeString, value)
		_node.ActorAvatarURL = value
	}
	if value, ok := _c.mutation.Text(); ok {
		_spec.SetField(steerrequest.FieldText, field.TypeString, value)
		_node.Text = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(steerrequest.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   steerrequest.SessionTable,
			Columns: []string{steerrequest.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agentsession.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.agent_session_steer_requests = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SteerRequestCreateBulk is the builder for creating many SteerRequest entities in bulk.
type SteerRequestCreateBulk struct {
	config
	err      error
	builders []*SteerRequestCreate
}

// Save creates the SteerRequest entities in the database.
func (_c *SteerRequestCreateBulk) Save(ctx context.Context) ([]*SteerRequest, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SteerRequest, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SteerRequestMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SteerRequestCreateBulk) SaveX(ctx context.Context) []*SteerRequest {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SteerRequestCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SteerRequestCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
