// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/francogalfre/coop/apps/relay/internal/db/ent/agentsession"
	"github.com/francogalfre/coop/apps/relay/internal/db/ent/steerrequest"
)

// SteerRequest is the model entity for the SteerRequest schema.
type SteerRequest struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// ActorID holds the value of the "actor_id" field.
	ActorID string `json:"actor_id,omitempty"`
	// ActorDisplayName holds the value of the "actor_display_name" field.
	ActorDisplayName string `json:"actor_display_name,omitempty"`
	// ActorAvatarURL holds the value of the "actor_avatar_url" field.
	ActorAvatarURL string `json:"actor_avatar_url,omitempty"`
	// Text holds the value of the "text" field.
	Text string `json:"text,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SteerRequestQuery when eager-loading is set.
	Edges                        SteerRequestEdges `json:"edges"`
	agent_session_steer_requests *string
	selectValues                 sql.SelectValues
}

// SteerRequestEdges holds the relations/edges for other nodes in the graph.
type SteerRequestEdges struct {
	// Session holds the value of the session edge.
	Session *AgentSession `json:"session,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// SessionOrErr returns the Session value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SteerRequestEdges) SessionOrErr() (*AgentSession, error) {
	if e.Session != nil {
		return e.Session, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: agentsession.Label}
	}
	return nil, &NotLoadedError{edge: "session"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SteerRequest) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case steerrequest.FieldID, steerrequest.FieldActorID, steerrequest.FieldActorDisplayName, steerrequest.FieldActorAvatarURL, steerrequest.FieldText:
			values[i] = new(sql.NullString)
		case steerrequest.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case steerrequest.ForeignKeys[0]: // agent_session_steer_requests
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SteerRequest fields.
func (_m *SteerRequest) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case steerrequest.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case steerrequest.FieldActorID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field actor_id", values[i])
			} else if value.Valid {
				_m.ActorID = value.String
			}
		case steerrequest.FieldActorDisplayName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field actor_display_name", values[i])
			} else if value.Valid {
				_m.ActorDisplayName = value.String
			}
		case steerrequest.FieldActorAvatarURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field actor_avatar_url", values[i])
			} else if value.Valid {
				_m.ActorAvatarURL = value.String
			}
		case steerrequest.FieldText:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field text", values[i])
			} else if value.Valid {
				_m.Text = value.String
			}
		case steerrequest.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case steerrequest.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field agent_session_steer_requests", values[i])
			} else if value.Valid {
				_m.agent_session_steer_requests = new(string)
				*_m.agent_session_steer_requests = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SteerRequest.
// This includes values selected through modifiers, order, etc.
func (_m *SteerRequest) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySession queries the "session" edge of the SteerRequest entity.
func (_m *SteerRequest) QuerySession() *AgentSessionQuery {
	return NewSteerRequestClient(_m.config).QuerySession(_m)
}

// Update returns a builder for updating this SteerRequest.
// Note that you need to call SteerRequest.Unwrap() before calling this method if this SteerRequest
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SteerRequest) Update() *SteerRequestUpdateOne {
	return NewSteerRequestClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SteerRequest entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SteerRequest) Unwrap() *SteerRequest {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SteerRequest is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SteerRequest) String() string {
	var builder strings.Builder
	builder.WriteString("SteerRequest(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("actor_id=")
	builder.WriteString(_m.ActorID)
	builder.WriteString(", ")
	builder.WriteString("actor_display_name=")
	builder.WriteString(_m.ActorDisplayName)
	builder.WriteString(", ")
	builder.WriteString("actor_avatar_url=")
	builder.WriteString(_m.ActorAvatarURL)
	builder.WriteString(", ")
	builder.WriteString("text=")
	builder.WriteString(_m.Text)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SteerRequests is a parsable slice of SteerRequest.
type SteerRequests []*SteerRequest
