// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/francogalfre/coop/apps/relay/internal/db/ent/predicate"
	"github.com/francogalfre/coop/apps/relay/internal/db/ent/steerrequest"
)

// SteerRequestDelete is the builder for deleting a SteerRequest entity.
type SteerRequestDelete struct {
	config
	hooks    []Hook
	mutation *SteerRequestMutation
}

// Where appends a list predicates to the SteerRequestDelete builder.
func (_d *SteerRequestDelete) Where(ps ...predicate.SteerRequest) *SteerRequestDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *SteerRequestDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SteerRequestDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *SteerRequestDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(steerrequest.Table, sqlgraph.NewFieldSpec(steerrequest.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// SteerRequestDeleteOne is the builder for deleting a single SteerRequest entity.
type SteerRequestDeleteOne struct {
	_d *SteerRequestDelete
}

// Where appends a list predicates to the SteerRequestDelete builder.
func (_d *SteerRequestDeleteOne) Where(ps ...predicate.SteerRequest) *SteerRequestDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *SteerRequestDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{steerrequest.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SteerRequestDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
