// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/francogalfre/coop/apps/relay/internal/db/ent/agentsession"
	"github.com/francogalfre/coop/apps/relay/internal/db/ent/takeover"
)

// TakeoverCreate is the builder for creating a Takeover entity.
type TakeoverCreate struct {
	config
	mutation *TakeoverMutation
	hooks    []Hook
}

// SetActorID sets the "actor_id" field.
func (_c *TakeoverCreate) SetActorID(v string) *TakeoverCreate {
	_c.mutation.SetActorID(v)
	return _c
}

// SetActorDisplayName sets the "actor_display_name" field.
func (_c *TakeoverCreate) SetActorDisplayName(v string) *TakeoverCreate {
	_c.mutation.SetActorDisplayName(v)
	return _c
}

// SetNillableActorDisplayName sets the "actor_display_name" field if the given value is not nil.
func (_c *TakeoverCreate) SetNillableActorDisplayName(v *string) *TakeoverCreate {
	if v != nil {
		_c.SetActorDisplayName(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TakeoverCreate) SetCreatedAt(v time.Time) *TakeoverCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TakeoverCreate) SetNillableCreatedAt(v *time.Time) *TakeoverCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *TakeoverCreate) SetID(v string) *TakeoverCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetSessionID sets the "session" edge to the AgentSession entity by ID.
func (_c *TakeoverCreate) SetSessionID(id string) *TakeoverCreate {
	_c.mutation.SetSessionID(id)
	return _c
}

// SetSession sets the "session" edge to the AgentSession entity.
func (_c *TakeoverCreate) SetSession(v *AgentSession) *TakeoverCreate {
	return _c.SetSessionID(v.ID)
}

// Mutation returns the TakeoverMutation object of the builder.
func (_c *TakeoverCreate) Mutation() *TakeoverMutation {
	return _c.mutation
}

// Save creates the Takeover in the database.
func (_c *TakeoverCreate) Save(ctx context.Context) (*Takeover, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TakeoverCreate) SaveX(ctx context.Context) *Takeover {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TakeoverCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TakeoverCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TakeoverCreate) defaults() {
	if _, ok := _c.mutation.ActorDisplayName(); !ok {
		v := takeover.DefaultActorDisplayName
		_c.mutation.SetActorDisplayName(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := takeover.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TakeoverCreate) check() error {
	if _, ok := _c.mutation.ActorID(); !ok {
		return &ValidationError{Name: "actor_id", err: errors.New(`ent: missing required field "Takeover.actor_id"`)}
	}
	if v, ok := _c.mutation.ActorID(); ok {
		if err := takeover.ActorIDValidator(v); err != nil {
			return &ValidationError{Name: "actor_id", err: fmt.Errorf(`ent: validator failed for field "Takeover.actor_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ActorDisplayName(); !ok {
		return &ValidationError{Name: "actor_display_name", err: errors.New(`ent: missing required field "Takeover.actor_display_name"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Takeover.created_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := takeover.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Takeover.id": %w`, err)}
		}
	}
	if len(_c.mutation.SessionIDs()) == 0 {
		return &ValidationError{Name: "session", err: errors.New(`ent: missing required edge "Takeover.session"`)}
	}
	return nil
}

func (_c *TakeoverCreate) sqlSave(ctx context.Context) (*Takeover, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Takeover.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TakeoverCreate) createSpec() (*Takeover, *sqlgraph.CreateSpec) {
	var (
		_node = &Takeover{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(takeover.Table, sqlgraph.NewFieldSpec(takeover.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.ActorID(); ok {
		_spec.SetField(takeover.FieldActorID, field.TypeString, value)
		_node.ActorID = value
	}
	if value, ok := _c.mutation.ActorDisplayName(); ok {
		_spec.SetField(takeover.FieldActorDisplayName, field.TypeString, value)
		_node.ActorDisplayName = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(takeover.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   takeover.SessionTable,
			Columns: []string{takeover.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agentsession.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.agent_session_takeover = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TakeoverCreateBulk is the builder for creating many Takeover entities in bulk.
type TakeoverCreateBulk struct {
	config
	err      error
	builders []*TakeoverCreate
}

// Save creates the Takeover entities in the database.
func (_c *TakeoverCreateBulk) Save(ctx context.Context) ([]*Takeover, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Takeover, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TakeoverMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TakeoverCreateBulk) SaveX(ctx context.Context) []*Takeover {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TakeoverCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TakeoverCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
