// Code generated by ent, DO NOT EDIT.

package projectnote

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the projectnote type in the database.
	Label = "project_note"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAuthorID holds the string denoting the author_id field in the database.
	FieldAuthorID = "author_id"
	// FieldAuthorDisplayName holds the string denoting the author_display_name field in the database.
	FieldAuthorDisplayName = "author_display_name"
	// FieldAuthorAvatarURL holds the string denoting the author_avatar_url field in the database.
	FieldAuthorAvatarURL = "author_avatar_url"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// FieldSessionID holds the string denoting the session_id field in the database.
	FieldSessionID = "session_id"
	// FieldText holds the string denoting the text field in the database.
	FieldText = "text"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeProject holds the string denoting the project edge name in mutations.
	EdgeProject = "project"
	// Table holds the table name of the projectnote in the database.
	Table = "project_notes"
	// ProjectTable is the table that holds the project relation/edge.
	ProjectTable = "project_notes"
	// ProjectInverseTable is the table name for the Project entity.
	// It exists in this package in order to avoid circular dependency with the "project" package.
	ProjectInverseTable = "projects"
	// ProjectColumn is the table column denoting the project relation/edge.
	ProjectColumn = "project_notes"
)

// Columns holds all SQL columns for projectnote fields.
var Columns = []string{
	FieldID,
	FieldAuthorID,
	FieldAuthorDisplayName,
	FieldAuthorAvatarURL,
	FieldSource,
	FieldSessionID,
	FieldText,
	FieldCreatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "project_notes"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"project_notes",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// AuthorIDValidator is a validator for the "author_id" field. It is called by the builders before save.
	AuthorIDValidator func(string) error
	// DefaultAuthorDisplayName holds the default value on creation for the "author_display_name" field.
	DefaultAuthorDisplayName string
	// DefaultAuthorAvatarURL holds the default value on creation for the "author_avatar_url" field.
	DefaultAuthorAvatarURL string
	// DefaultSource holds the default value on creation for the "source" field.
	DefaultSource string
	// TextValidator is a validator for the "text" field. It is called by the builders before save.
	TextValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the ProjectNote queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByAuthorID orders the results by the author_id field.
func ByAuthorID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuthorID, opts...).ToFunc()
}

// ByAuthorDisplayName orders the results by the author_display_name field.
func ByAuthorDisplayName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuthorDisplayName, opts...).ToFunc()
}

// ByAuthorAvatarURL orders the results by the author_avatar_url field.
func ByAuthorAvatarURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuthorAvatarURL, opts...).ToFunc()
}

// BySource orders the results by the source field.
func BySource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSource, opts...).ToFunc()
}

// BySessionID orders the results by the session_id field.
func BySessionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSessionID, opts...).ToFunc()
}

// ByText orders the results by the text field.
func ByText(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldText, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByProjectField orders the results by project field.
func ByProjectField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProjectStep(), sql.OrderByField(field, opts...))
	}
}
func newProjectStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProjectInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ProjectTable, ProjectColumn),
	)
}
