// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AgentsColumns holds the columns for the "agents" table.
	AgentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "display_name", Type: field.TypeString, Default: ""},
		{Name: "created_by", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "project_agents", Type: field.TypeInt},
	}
	// AgentsTable holds the schema information for the "agents" table.
	AgentsTable = &schema.Table{
		Name:       "agents",
		Columns:    AgentsColumns,
		PrimaryKey: []*schema.Column{AgentsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "agents_projects_agents",
				Columns:    []*schema.Column{AgentsColumns[5]},
				RefColumns: []*schema.Column{ProjectsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "agent_name_project_agents",
				Unique:  true,
				Columns: []*schema.Column{AgentsColumns[1], AgentsColumns[5]},
			},
		},
	}
	// AgentSessionsColumns holds the columns for the "agent_sessions" table.
	AgentSessionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "owner_id", Type: field.TypeString},
		{Name: "repo", Type: field.TypeString, Default: ""},
		{Name: "cwd", Type: field.TypeString, Default: ""},
		{Name: "harness", Type: field.TypeString, Default: ""},
		{Name: "status", Type: field.TypeString, Default: "live"},
		{Name: "mode", Type: field.TypeString, Default: "auto"},
		{Name: "next_seq", Type: field.TypeInt, Default: 0},
		{Name: "started_at", Type: field.TypeTime},
		{Name: "ended_at", Type: field.TypeTime, Nullable: true},
		{Name: "agent_sessions", Type: field.TypeString, Nullable: true},
		{Name: "project_sessions", Type: field.TypeInt},
	}
	// AgentSessionsTable holds the schema information for the "agent_sessions" table.
	AgentSessionsTable = &schema.Table{
		Name:       "agent_sessions",
		Columns:    AgentSessionsColumns,
		PrimaryKey: []*schema.Column{AgentSessionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "agent_sessions_agents_sessions",
				Columns:    []*schema.Column{AgentSessionsColumns[10]},
				RefColumns: []*schema.Column{AgentsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "agent_sessions_projects_sessions",
				Columns:    []*schema.Column{AgentSessionsColumns[11]},
				RefColumns: []*schema.Column{ProjectsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// CliCredentialsColumns holds the columns for the "cli_credentials" table.
	CliCredentialsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "user_id", Type: field.TypeString},
		{Name: "display_name", Type: field.TypeString, Default: ""},
		{Name: "token_hash", Type: field.TypeBytes, Unique: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "last_used_at", Type: field.TypeTime, Nullable: true},
		{Name: "expires_at", Type: field.TypeTime, Nullable: true},
	}
	// CliCredentialsTable holds the schema information for the "cli_credentials" table.
	CliCredentialsTable = &schema.Table{
		Name:       "cli_credentials",
		Columns:    CliCredentialsColumns,
		PrimaryKey: []*schema.Column{CliCredentialsColumns[0]},
	}
	// EventsColumns holds the columns for the "events" table.
	EventsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "seq", Type: field.TypeInt},
		{Name: "data", Type: field.TypeBytes},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "agent_session_events", Type: field.TypeString},
	}
	// EventsTable holds the schema information for the "events" table.
	EventsTable = &schema.Table{
		Name:       "events",
		Columns:    EventsColumns,
		PrimaryKey: []*schema.Column{EventsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "events_agent_sessions_events",
				Columns:    []*schema.Column{EventsColumns[4]},
				RefColumns: []*schema.Column{AgentSessionsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "event_seq_agent_session_events",
				Unique:  true,
				Columns: []*schema.Column{EventsColumns[1], EventsColumns[4]},
			},
		},
	}
	// ProjectsColumns holds the columns for the "projects" table.
	ProjectsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "slug", Type: field.TypeString, Unique: true},
		{Name: "created_by", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
	}
	// ProjectsTable holds the schema information for the "projects" table.
	ProjectsTable = &schema.Table{
		Name:       "projects",
		Columns:    ProjectsColumns,
		PrimaryKey: []*schema.Column{ProjectsColumns[0]},
	}
	// ProjectInvitesColumns holds the columns for the "project_invites" table.
	ProjectInvitesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "token_hash", Type: field.TypeBytes, Unique: true},
		{Name: "created_by", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "revoked_at", Type: field.TypeTime, Nullable: true},
		{Name: "project_invites", Type: field.TypeInt},
	}
	// ProjectInvitesTable holds the schema information for the "project_invites" table.
	ProjectInvitesTable = &schema.Table{
		Name:       "project_invites",
		Columns:    ProjectInvitesColumns,
		PrimaryKey: []*schema.Column{ProjectInvitesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "project_invites_projects_invites",
				Columns:    []*schema.Column{ProjectInvitesColumns[6]},
				RefColumns: []*schema.Column{ProjectsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// ProjectMembersColumns holds the columns for the "project_members" table.
	ProjectMembersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "user_id", Type: field.TypeString},
		{Name: "role", Type: field.TypeString},
		{Name: "joined_at", Type: field.TypeTime},
		{Name: "project_members", Type: field.TypeInt},
	}
	// ProjectMembersTable holds the schema information for the "project_members" table.
	ProjectMembersTable = &schema.Table{
		Name:       "project_members",
		Columns:    ProjectMembersColumns,
		PrimaryKey: []*schema.Column{ProjectMembersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "project_members_projects_members",
				Columns:    []*schema.Column{ProjectMembersColumns[4]},
				RefColumns: []*schema.Column{ProjectsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "projectmember_user_id_project_members",
				Unique:  true,
				Columns: []*schema.Column{ProjectMembersColumns[1], ProjectMembersColumns[4]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AgentsTable,
		AgentSessionsTable,
		CliCredentialsTable,
		EventsTable,
		ProjectsTable,
		ProjectInvitesTable,
		ProjectMembersTable,
	}
)

func init() {
	AgentsTable.ForeignKeys[0].RefTable = ProjectsTable
	AgentSessionsTable.ForeignKeys[0].RefTable = AgentsTable
	AgentSessionsTable.ForeignKeys[1].RefTable = ProjectsTable
	EventsTable.ForeignKeys[0].RefTable = AgentSessionsTable
	ProjectInvitesTable.ForeignKeys[0].RefTable = ProjectsTable
	ProjectMembersTable.ForeignKeys[0].RefTable = ProjectsTable
}
