// Code generated by ent, DO NOT EDIT.

package agentsession

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the agentsession type in the database.
	Label = "agent_session"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldOwnerID holds the string denoting the owner_id field in the database.
	FieldOwnerID = "owner_id"
	// FieldRepo holds the string denoting the repo field in the database.
	FieldRepo = "repo"
	// FieldCwd holds the string denoting the cwd field in the database.
	FieldCwd = "cwd"
	// FieldHarness holds the string denoting the harness field in the database.
	FieldHarness = "harness"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldMode holds the string denoting the mode field in the database.
	FieldMode = "mode"
	// FieldNextSeq holds the string denoting the next_seq field in the database.
	FieldNextSeq = "next_seq"
	// FieldStartedAt holds the string denoting the started_at field in the database.
	FieldStartedAt = "started_at"
	// FieldEndedAt holds the string denoting the ended_at field in the database.
	FieldEndedAt = "ended_at"
	// EdgeProject holds the string denoting the project edge name in mutations.
	EdgeProject = "project"
	// EdgeEvents holds the string denoting the events edge name in mutations.
	EdgeEvents = "events"
	// Table holds the table name of the agentsession in the database.
	Table = "agent_sessions"
	// ProjectTable is the table that holds the project relation/edge.
	ProjectTable = "agent_sessions"
	// ProjectInverseTable is the table name for the Project entity.
	// It exists in this package in order to avoid circular dependency with the "project" package.
	ProjectInverseTable = "projects"
	// ProjectColumn is the table column denoting the project relation/edge.
	ProjectColumn = "project_sessions"
	// EventsTable is the table that holds the events relation/edge.
	EventsTable = "events"
	// EventsInverseTable is the table name for the Event entity.
	// It exists in this package in order to avoid circular dependency with the "event" package.
	EventsInverseTable = "events"
	// EventsColumn is the table column denoting the events relation/edge.
	EventsColumn = "agent_session_events"
)

// Columns holds all SQL columns for agentsession fields.
var Columns = []string{
	FieldID,
	FieldOwnerID,
	FieldRepo,
	FieldCwd,
	FieldHarness,
	FieldStatus,
	FieldMode,
	FieldNextSeq,
	FieldStartedAt,
	FieldEndedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "agent_sessions"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"project_sessions",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// OwnerIDValidator is a validator for the "owner_id" field. It is called by the builders before save.
	OwnerIDValidator func(string) error
	// DefaultRepo holds the default value on creation for the "repo" field.
	DefaultRepo string
	// DefaultCwd holds the default value on creation for the "cwd" field.
	DefaultCwd string
	// DefaultHarness holds the default value on creation for the "harness" field.
	DefaultHarness string
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// DefaultMode holds the default value on creation for the "mode" field.
	DefaultMode string
	// DefaultNextSeq holds the default value on creation for the "next_seq" field.
	DefaultNextSeq int
	// NextSeqValidator is a validator for the "next_seq" field. It is called by the builders before save.
	NextSeqValidator func(int) error
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the AgentSession queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByOwnerID orders the results by the owner_id field.
func ByOwnerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOwnerID, opts...).ToFunc()
}

// ByRepo orders the results by the repo field.
func ByRepo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRepo, opts...).ToFunc()
}

// ByCwd orders the results by the cwd field.
func ByCwd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCwd, opts...).ToFunc()
}

// ByHarness orders the results by the harness field.
func ByHarness(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHarness, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByMode orders the results by the mode field.
func ByMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMode, opts...).ToFunc()
}

// ByNextSeq orders the results by the next_seq field.
func ByNextSeq(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNextSeq, opts...).ToFunc()
}

// ByStartedAt orders the results by the started_at field.
func ByStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedAt, opts...).ToFunc()
}

// ByEndedAt orders the results by the ended_at field.
func ByEndedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndedAt, opts...).ToFunc()
}

// ByProjectField orders the results by project field.
func ByProjectField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProjectStep(), sql.OrderByField(field, opts...))
	}
}

// ByEventsCount orders the results by events count.
func ByEventsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newEventsStep(), opts...)
	}
}

// ByEvents orders the results by events terms.
func ByEvents(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEventsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newProjectStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProjectInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ProjectTable, ProjectColumn),
	)
}
func newEventsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EventsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, EventsTable, EventsColumn),
	)
}
