// Code generated by ent, DO NOT EDIT.

package agentsession

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/francogalfre/coop/apps/relay/internal/db/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldContainsFold(FieldID, id))
}

// OwnerID applies equality check predicate on the "owner_id" field. It's identical to OwnerIDEQ.
func OwnerID(v string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldEQ(FieldOwnerID, v))
}

// Repo applies equality check predicate on the "repo" field. It's identical to RepoEQ.
func Repo(v string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldEQ(FieldRepo, v))
}

// Cwd applies equality check predicate on the "cwd" field. It's identical to CwdEQ.
func Cwd(v string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldEQ(FieldCwd, v))
}

// Harness applies equality check predicate on the "harness" field. It's identical to HarnessEQ.
func Harness(v string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldEQ(FieldHarness, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldEQ(FieldStatus, v))
}

// Mode applies equality check predicate on the "mode" field. It's identical to ModeEQ.
func Mode(v string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldEQ(FieldMode, v))
}

// NextSeq applies equality check predicate on the "next_seq" field. It's identical to NextSeqEQ.
func NextSeq(v int) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldEQ(FieldNextSeq, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldEQ(FieldStartedAt, v))
}

// EndedAt applies equality check predicate on the "ended_at" field. It's identical to EndedAtEQ.
func EndedAt(v time.Time) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldEQ(FieldEndedAt, v))
}

// OwnerIDEQ applies the EQ predicate on the "owner_id" field.
func OwnerIDEQ(v string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldEQ(FieldOwnerID, v))
}

// OwnerIDNEQ applies the NEQ predicate on the "owner_id" field.
func OwnerIDNEQ(v string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldNEQ(FieldOwnerID, v))
}

// OwnerIDIn applies the In predicate on the "owner_id" field.
func OwnerIDIn(vs ...string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldIn(FieldOwnerID, vs...))
}

// OwnerIDNotIn applies the NotIn predicate on the "owner_id" field.
func OwnerIDNotIn(vs ...string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldNotIn(FieldOwnerID, vs...))
}

// OwnerIDGT applies the GT predicate on the "owner_id" field.
func OwnerIDGT(v string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldGT(FieldOwnerID, v))
}

// OwnerIDGTE applies the GTE predicate on the "owner_id" field.
func OwnerIDGTE(v string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldGTE(FieldOwnerID, v))
}

// OwnerIDLT applies the LT predicate on the "owner_id" field.
func OwnerIDLT(v string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldLT(FieldOwnerID, v))
}

// OwnerIDLTE applies the LTE predicate on the "owner_id" field.
func OwnerIDLTE(v string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldLTE(FieldOwnerID, v))
}

// OwnerIDContains applies the Contains predicate on the "owner_id" field.
func OwnerIDContains(v string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldContains(FieldOwnerID, v))
}

// OwnerIDHasPrefix applies the HasPrefix predicate on the "owner_id" field.
func OwnerIDHasPrefix(v string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldHasPrefix(FieldOwnerID, v))
}

// OwnerIDHasSuffix applies the HasSuffix predicate on the "owner_id" field.
func OwnerIDHasSuffix(v string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldHasSuffix(FieldOwnerID, v))
}

// OwnerIDEqualFold applies the EqualFold predicate on the "owner_id" field.
func OwnerIDEqualFold(v string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldEqualFold(FieldOwnerID, v))
}

// OwnerIDContainsFold applies the ContainsFold predicate on the "owner_id" field.
func OwnerIDContainsFold(v string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldContainsFold(FieldOwnerID, v))
}

// RepoEQ applies the EQ predicate on the "repo" field.
func RepoEQ(v string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldEQ(FieldRepo, v))
}

// RepoNEQ applies the NEQ predicate on the "repo" field.
func RepoNEQ(v string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldNEQ(FieldRepo, v))
}

// RepoIn applies the In predicate on the "repo" field.
func RepoIn(vs ...string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldIn(FieldRepo, vs...))
}

// RepoNotIn applies the NotIn predicate on the "repo" field.
func RepoNotIn(vs ...string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldNotIn(FieldRepo, vs...))
}

// RepoGT applies the GT predicate on the "repo" field.
func RepoGT(v string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldGT(FieldRepo, v))
}

// RepoGTE applies the GTE predicate on the "repo" field.
func RepoGTE(v string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldGTE(FieldRepo, v))
}

// RepoLT applies the LT predicate on the "repo" field.
func RepoLT(v string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldLT(FieldRepo, v))
}

// RepoLTE applies the LTE predicate on the "repo" field.
func RepoLTE(v string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldLTE(FieldRepo, v))
}

// RepoContains applies the Contains predicate on the "repo" field.
func RepoContains(v string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldContains(FieldRepo, v))
}

// RepoHasPrefix applies the HasPrefix predicate on the "repo" field.
func RepoHasPrefix(v string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldHasPrefix(FieldRepo, v))
}

// RepoHasSuffix applies the HasSuffix predicate on the "repo" field.
func RepoHasSuffix(v string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldHasSuffix(FieldRepo, v))
}

// RepoEqualFold applies the EqualFold predicate on the "repo" field.
func RepoEqualFold(v string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldEqualFold(FieldRepo, v))
}

// RepoContainsFold applies the ContainsFold predicate on the "repo" field.
func RepoContainsFold(v string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldContainsFold(FieldRepo, v))
}

// CwdEQ applies the EQ predicate on the "cwd" field.
func CwdEQ(v string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldEQ(FieldCwd, v))
}

// CwdNEQ applies the NEQ predicate on the "cwd" field.
func CwdNEQ(v string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldNEQ(FieldCwd, v))
}

// CwdIn applies the In predicate on the "cwd" field.
func CwdIn(vs ...string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldIn(FieldCwd, vs...))
}

// CwdNotIn applies the NotIn predicate on the "cwd" field.
func CwdNotIn(vs ...string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldNotIn(FieldCwd, vs...))
}

// CwdGT applies the GT predicate on the "cwd" field.
func CwdGT(v string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldGT(FieldCwd, v))
}

// CwdGTE applies the GTE predicate on the "cwd" field.
func CwdGTE(v string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldGTE(FieldCwd, v))
}

// CwdLT applies the LT predicate on the "cwd" field.
func CwdLT(v string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldLT(FieldCwd, v))
}

// CwdLTE applies the LTE predicate on the "cwd" field.
func CwdLTE(v string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldLTE(FieldCwd, v))
}

// CwdContains applies the Contains predicate on the "cwd" field.
func CwdContains(v string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldContains(FieldCwd, v))
}

// CwdHasPrefix applies the HasPrefix predicate on the "cwd" field.
func CwdHasPrefix(v string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldHasPrefix(FieldCwd, v))
}

// CwdHasSuffix applies the HasSuffix predicate on the "cwd" field.
func CwdHasSuffix(v string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldHasSuffix(FieldCwd, v))
}

// CwdEqualFold applies the EqualFold predicate on the "cwd" field.
func CwdEqualFold(v string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldEqualFold(FieldCwd, v))
}

// CwdContainsFold applies the ContainsFold predicate on the "cwd" field.
func CwdContainsFold(v string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldContainsFold(FieldCwd, v))
}

// HarnessEQ applies the EQ predicate on the "harness" field.
func HarnessEQ(v string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldEQ(FieldHarness, v))
}

// HarnessNEQ applies the NEQ predicate on the "harness" field.
func HarnessNEQ(v string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldNEQ(FieldHarness, v))
}

// HarnessIn applies the In predicate on the "harness" field.
func HarnessIn(vs ...string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldIn(FieldHarness, vs...))
}

// HarnessNotIn applies the NotIn predicate on the "harness" field.
func HarnessNotIn(vs ...string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldNotIn(FieldHarness, vs...))
}

// HarnessGT applies the GT predicate on the "harness" field.
func HarnessGT(v string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldGT(FieldHarness, v))
}

// HarnessGTE applies the GTE predicate on the "harness" field.
func HarnessGTE(v string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldGTE(FieldHarness, v))
}

// HarnessLT applies the LT predicate on the "harness" field.
func HarnessLT(v string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldLT(FieldHarness, v))
}

// HarnessLTE applies the LTE predicate on the "harness" field.
func HarnessLTE(v string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldLTE(FieldHarness, v))
}

// HarnessContains applies the Contains predicate on the "harness" field.
func HarnessContains(v string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldContains(FieldHarness, v))
}

// HarnessHasPrefix applies the HasPrefix predicate on the "harness" field.
func HarnessHasPrefix(v string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldHasPrefix(FieldHarness, v))
}

// HarnessHasSuffix applies the HasSuffix predicate on the "harness" field.
func HarnessHasSuffix(v string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldHasSuffix(FieldHarness, v))
}

// HarnessEqualFold applies the EqualFold predicate on the "harness" field.
func HarnessEqualFold(v string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldEqualFold(FieldHarness, v))
}

// HarnessContainsFold applies the ContainsFold predicate on the "harness" field.
func HarnessContainsFold(v string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldContainsFold(FieldHarness, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldContainsFold(FieldStatus, v))
}

// ModeEQ applies the EQ predicate on the "mode" field.
func ModeEQ(v string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldEQ(FieldMode, v))
}

// ModeNEQ applies the NEQ predicate on the "mode" field.
func ModeNEQ(v string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldNEQ(FieldMode, v))
}

// ModeIn applies the In predicate on the "mode" field.
func ModeIn(vs ...string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldIn(FieldMode, vs...))
}

// ModeNotIn applies the NotIn predicate on the "mode" field.
func ModeNotIn(vs ...string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldNotIn(FieldMode, vs...))
}

// ModeGT applies the GT predicate on the "mode" field.
func ModeGT(v string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldGT(FieldMode, v))
}

// ModeGTE applies the GTE predicate on the "mode" field.
func ModeGTE(v string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldGTE(FieldMode, v))
}

// ModeLT applies the LT predicate on the "mode" field.
func ModeLT(v string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldLT(FieldMode, v))
}

// ModeLTE applies the LTE predicate on the "mode" field.
func ModeLTE(v string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldLTE(FieldMode, v))
}

// ModeContains applies the Contains predicate on the "mode" field.
func ModeContains(v string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldContains(FieldMode, v))
}

// ModeHasPrefix applies the HasPrefix predicate on the "mode" field.
func ModeHasPrefix(v string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldHasPrefix(FieldMode, v))
}

// ModeHasSuffix applies the HasSuffix predicate on the "mode" field.
func ModeHasSuffix(v string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldHasSuffix(FieldMode, v))
}

// ModeEqualFold applies the EqualFold predicate on the "mode" field.
func ModeEqualFold(v string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldEqualFold(FieldMode, v))
}

// ModeContainsFold applies the ContainsFold predicate on the "mode" field.
func ModeContainsFold(v string) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldContainsFold(FieldMode, v))
}

// NextSeqEQ applies the EQ predicate on the "next_seq" field.
func NextSeqEQ(v int) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldEQ(FieldNextSeq, v))
}

// NextSeqNEQ applies the NEQ predicate on the "next_seq" field.
func NextSeqNEQ(v int) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldNEQ(FieldNextSeq, v))
}

// NextSeqIn applies the In predicate on the "next_seq" field.
func NextSeqIn(vs ...int) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldIn(FieldNextSeq, vs...))
}

// NextSeqNotIn applies the NotIn predicate on the "next_seq" field.
func NextSeqNotIn(vs ...int) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldNotIn(FieldNextSeq, vs...))
}

// NextSeqGT applies the GT predicate on the "next_seq" field.
func NextSeqGT(v int) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldGT(FieldNextSeq, v))
}

// NextSeqGTE applies the GTE predicate on the "next_seq" field.
func NextSeqGTE(v int) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldGTE(FieldNextSeq, v))
}

// NextSeqLT applies the LT predicate on the "next_seq" field.
func NextSeqLT(v int) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldLT(FieldNextSeq, v))
}

// NextSeqLTE applies the LTE predicate on the "next_seq" field.
func NextSeqLTE(v int) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldLTE(FieldNextSeq, v))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldLTE(FieldStartedAt, v))
}

// EndedAtEQ applies the EQ predicate on the "ended_at" field.
func EndedAtEQ(v time.Time) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldEQ(FieldEndedAt, v))
}

// EndedAtNEQ applies the NEQ predicate on the "ended_at" field.
func EndedAtNEQ(v time.Time) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldNEQ(FieldEndedAt, v))
}

// EndedAtIn applies the In predicate on the "ended_at" field.
func EndedAtIn(vs ...time.Time) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldIn(FieldEndedAt, vs...))
}

// EndedAtNotIn applies the NotIn predicate on the "ended_at" field.
func EndedAtNotIn(vs ...time.Time) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldNotIn(FieldEndedAt, vs...))
}

// EndedAtGT applies the GT predicate on the "ended_at" field.
func EndedAtGT(v time.Time) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldGT(FieldEndedAt, v))
}

// EndedAtGTE applies the GTE predicate on the "ended_at" field.
func EndedAtGTE(v time.Time) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldGTE(FieldEndedAt, v))
}

// EndedAtLT applies the LT predicate on the "ended_at" field.
func EndedAtLT(v time.Time) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldLT(FieldEndedAt, v))
}

// EndedAtLTE applies the LTE predicate on the "ended_at" field.
func EndedAtLTE(v time.Time) predicate.AgentSession {
	return predicate.AgentSession(sql.FieldLTE(FieldEndedAt, v))
}

// EndedAtIsNil applies the IsNil predicate on the "ended_at" field.
func EndedAtIsNil() predicate.AgentSession {
	return predicate.AgentSession(sql.FieldIsNull(FieldEndedAt))
}

// EndedAtNotNil applies the NotNil predicate on the "ended_at" field.
func EndedAtNotNil() predicate.AgentSession {
	return predicate.AgentSession(sql.FieldNotNull(FieldEndedAt))
}

// HasProject applies the HasEdge predicate on the "project" edge.
func HasProject() predicate.AgentSession {
	return predicate.AgentSession(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ProjectTable, ProjectColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProjectWith applies the HasEdge predicate on the "project" edge with a given conditions (other predicates).
func HasProjectWith(preds ...predicate.Project) predicate.AgentSession {
	return predicate.AgentSession(func(s *sql.Selector) {
		step := newProjectStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasEvents applies the HasEdge predicate on the "events" edge.
func HasEvents() predicate.AgentSession {
	return predicate.AgentSession(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, EventsTable, EventsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEventsWith applies the HasEdge predicate on the "events" edge with a given conditions (other predicates).
func HasEventsWith(preds ...predicate.Event) predicate.AgentSession {
	return predicate.AgentSession(func(s *sql.Selector) {
		step := newEventsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AgentSession) predicate.AgentSession {
	return predicate.AgentSession(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AgentSession) predicate.AgentSession {
	return predicate.AgentSession(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AgentSession) predicate.AgentSession {
	return predicate.AgentSession(sql.NotPredicates(p))
}
