// Code generated by ent, DO NOT EDIT.

package project

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/francogalfre/coop/apps/relay/internal/db/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Project {
	return predicate.Project(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Project {
	return predicate.Project(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Project {
	return predicate.Project(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Project {
	return predicate.Project(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Project {
	return predicate.Project(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Project {
	return predicate.Project(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Project {
	return predicate.Project(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldName, v))
}

// Slug applies equality check predicate on the "slug" field. It's identical to SlugEQ.
func Slug(v string) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldSlug, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v string) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldCreatedAt, v))
}

// ContextText applies equality check predicate on the "context_text" field. It's identical to ContextTextEQ.
func ContextText(v string) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldContextText, v))
}

// ContextVersion applies equality check predicate on the "context_version" field. It's identical to ContextVersionEQ.
func ContextVersion(v int) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldContextVersion, v))
}

// ContextUpdatedBy applies equality check predicate on the "context_updated_by" field. It's identical to ContextUpdatedByEQ.
func ContextUpdatedBy(v string) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldContextUpdatedBy, v))
}

// ContextUpdatedAt applies equality check predicate on the "context_updated_at" field. It's identical to ContextUpdatedAtEQ.
func ContextUpdatedAt(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldContextUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Project {
	return predicate.Project(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Project {
	return predicate.Project(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Project {
	return predicate.Project(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Project {
	return predicate.Project(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Project {
	return predicate.Project(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Project {
	return predicate.Project(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Project {
	return predicate.Project(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Project {
	return predicate.Project(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Project {
	return predicate.Project(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Project {
	return predicate.Project(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Project {
	return predicate.Project(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Project {
	return predicate.Project(sql.FieldContainsFold(FieldName, v))
}

// SlugEQ applies the EQ predicate on the "slug" field.
func SlugEQ(v string) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldSlug, v))
}

// SlugNEQ applies the NEQ predicate on the "slug" field.
func SlugNEQ(v string) predicate.Project {
	return predicate.Project(sql.FieldNEQ(FieldSlug, v))
}

// SlugIn applies the In predicate on the "slug" field.
func SlugIn(vs ...string) predicate.Project {
	return predicate.Project(sql.FieldIn(FieldSlug, vs...))
}

// SlugNotIn applies the NotIn predicate on the "slug" field.
func SlugNotIn(vs ...string) predicate.Project {
	return predicate.Project(sql.FieldNotIn(FieldSlug, vs...))
}

// SlugGT applies the GT predicate on the "slug" field.
func SlugGT(v string) predicate.Project {
	return predicate.Project(sql.FieldGT(FieldSlug, v))
}

// SlugGTE applies the GTE predicate on the "slug" field.
func SlugGTE(v string) predicate.Project {
	return predicate.Project(sql.FieldGTE(FieldSlug, v))
}

// SlugLT applies the LT predicate on the "slug" field.
func SlugLT(v string) predicate.Project {
	return predicate.Project(sql.FieldLT(FieldSlug, v))
}

// SlugLTE applies the LTE predicate on the "slug" field.
func SlugLTE(v string) predicate.Project {
	return predicate.Project(sql.FieldLTE(FieldSlug, v))
}

// SlugContains applies the Contains predicate on the "slug" field.
func SlugContains(v string) predicate.Project {
	return predicate.Project(sql.FieldContains(FieldSlug, v))
}

// SlugHasPrefix applies the HasPrefix predicate on the "slug" field.
func SlugHasPrefix(v string) predicate.Project {
	return predicate.Project(sql.FieldHasPrefix(FieldSlug, v))
}

// SlugHasSuffix applies the HasSuffix predicate on the "slug" field.
func SlugHasSuffix(v string) predicate.Project {
	return predicate.Project(sql.FieldHasSuffix(FieldSlug, v))
}

// SlugEqualFold applies the EqualFold predicate on the "slug" field.
func SlugEqualFold(v string) predicate.Project {
	return predicate.Project(sql.FieldEqualFold(FieldSlug, v))
}

// SlugContainsFold applies the ContainsFold predicate on the "slug" field.
func SlugContainsFold(v string) predicate.Project {
	return predicate.Project(sql.FieldContainsFold(FieldSlug, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v string) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v string) predicate.Project {
	return predicate.Project(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...string) predicate.Project {
	return predicate.Project(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...string) predicate.Project {
	return predicate.Project(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v string) predicate.Project {
	return predicate.Project(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v string) predicate.Project {
	return predicate.Project(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v string) predicate.Project {
	return predicate.Project(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v string) predicate.Project {
	return predicate.Project(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByContains applies the Contains predicate on the "created_by" field.
func CreatedByContains(v string) predicate.Project {
	return predicate.Project(sql.FieldContains(FieldCreatedBy, v))
}

// CreatedByHasPrefix applies the HasPrefix predicate on the "created_by" field.
func CreatedByHasPrefix(v string) predicate.Project {
	return predicate.Project(sql.FieldHasPrefix(FieldCreatedBy, v))
}

// CreatedByHasSuffix applies the HasSuffix predicate on the "created_by" field.
func CreatedByHasSuffix(v string) predicate.Project {
	return predicate.Project(sql.FieldHasSuffix(FieldCreatedBy, v))
}

// CreatedByEqualFold applies the EqualFold predicate on the "created_by" field.
func CreatedByEqualFold(v string) predicate.Project {
	return predicate.Project(sql.FieldEqualFold(FieldCreatedBy, v))
}

// CreatedByContainsFold applies the ContainsFold predicate on the "created_by" field.
func CreatedByContainsFold(v string) predicate.Project {
	return predicate.Project(sql.FieldContainsFold(FieldCreatedBy, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Project {
	return predicate.Project(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Project {
	return predicate.Project(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldLTE(FieldCreatedAt, v))
}

// ContextTextEQ applies the EQ predicate on the "context_text" field.
func ContextTextEQ(v string) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldContextText, v))
}

// ContextTextNEQ applies the NEQ predicate on the "context_text" field.
func ContextTextNEQ(v string) predicate.Project {
	return predicate.Project(sql.FieldNEQ(FieldContextText, v))
}

// ContextTextIn applies the In predicate on the "context_text" field.
func ContextTextIn(vs ...string) predicate.Project {
	return predicate.Project(sql.FieldIn(FieldContextText, vs...))
}

// ContextTextNotIn applies the NotIn predicate on the "context_text" field.
func ContextTextNotIn(vs ...string) predicate.Project {
	return predicate.Project(sql.FieldNotIn(FieldContextText, vs...))
}

// ContextTextGT applies the GT predicate on the "context_text" field.
func ContextTextGT(v string) predicate.Project {
	return predicate.Project(sql.FieldGT(FieldContextText, v))
}

// ContextTextGTE applies the GTE predicate on the "context_text" field.
func ContextTextGTE(v string) predicate.Project {
	return predicate.Project(sql.FieldGTE(FieldContextText, v))
}

// ContextTextLT applies the LT predicate on the "context_text" field.
func ContextTextLT(v string) predicate.Project {
	return predicate.Project(sql.FieldLT(FieldContextText, v))
}

// ContextTextLTE applies the LTE predicate on the "context_text" field.
func ContextTextLTE(v string) predicate.Project {
	return predicate.Project(sql.FieldLTE(FieldContextText, v))
}

// ContextTextContains applies the Contains predicate on the "context_text" field.
func ContextTextContains(v string) predicate.Project {
	return predicate.Project(sql.FieldContains(FieldContextText, v))
}

// ContextTextHasPrefix applies the HasPrefix predicate on the "context_text" field.
func ContextTextHasPrefix(v string) predicate.Project {
	return predicate.Project(sql.FieldHasPrefix(FieldContextText, v))
}

// ContextTextHasSuffix applies the HasSuffix predicate on the "context_text" field.
func ContextTextHasSuffix(v string) predicate.Project {
	return predicate.Project(sql.FieldHasSuffix(FieldContextText, v))
}

// ContextTextEqualFold applies the EqualFold predicate on the "context_text" field.
func ContextTextEqualFold(v string) predicate.Project {
	return predicate.Project(sql.FieldEqualFold(FieldContextText, v))
}

// ContextTextContainsFold applies the ContainsFold predicate on the "context_text" field.
func ContextTextContainsFold(v string) predicate.Project {
	return predicate.Project(sql.FieldContainsFold(FieldContextText, v))
}

// ContextVersionEQ applies the EQ predicate on the "context_version" field.
func ContextVersionEQ(v int) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldContextVersion, v))
}

// ContextVersionNEQ applies the NEQ predicate on the "context_version" field.
func ContextVersionNEQ(v int) predicate.Project {
	return predicate.Project(sql.FieldNEQ(FieldContextVersion, v))
}

// ContextVersionIn applies the In predicate on the "context_version" field.
func ContextVersionIn(vs ...int) predicate.Project {
	return predicate.Project(sql.FieldIn(FieldContextVersion, vs...))
}

// ContextVersionNotIn applies the NotIn predicate on the "context_version" field.
func ContextVersionNotIn(vs ...int) predicate.Project {
	return predicate.Project(sql.FieldNotIn(FieldContextVersion, vs...))
}

// ContextVersionGT applies the GT predicate on the "context_version" field.
func ContextVersionGT(v int) predicate.Project {
	return predicate.Project(sql.FieldGT(FieldContextVersion, v))
}

// ContextVersionGTE applies the GTE predicate on the "context_version" field.
func ContextVersionGTE(v int) predicate.Project {
	return predicate.Project(sql.FieldGTE(FieldContextVersion, v))
}

// ContextVersionLT applies the LT predicate on the "context_version" field.
func ContextVersionLT(v int) predicate.Project {
	return predicate.Project(sql.FieldLT(FieldContextVersion, v))
}

// ContextVersionLTE applies the LTE predicate on the "context_version" field.
func ContextVersionLTE(v int) predicate.Project {
	return predicate.Project(sql.FieldLTE(FieldContextVersion, v))
}

// ContextUpdatedByEQ applies the EQ predicate on the "context_updated_by" field.
func ContextUpdatedByEQ(v string) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldContextUpdatedBy, v))
}

// ContextUpdatedByNEQ applies the NEQ predicate on the "context_updated_by" field.
func ContextUpdatedByNEQ(v string) predicate.Project {
	return predicate.Project(sql.FieldNEQ(FieldContextUpdatedBy, v))
}

// ContextUpdatedByIn applies the In predicate on the "context_updated_by" field.
func ContextUpdatedByIn(vs ...string) predicate.Project {
	return predicate.Project(sql.FieldIn(FieldContextUpdatedBy, vs...))
}

// ContextUpdatedByNotIn applies the NotIn predicate on the "context_updated_by" field.
func ContextUpdatedByNotIn(vs ...string) predicate.Project {
	return predicate.Project(sql.FieldNotIn(FieldContextUpdatedBy, vs...))
}

// ContextUpdatedByGT applies the GT predicate on the "context_updated_by" field.
func ContextUpdatedByGT(v string) predicate.Project {
	return predicate.Project(sql.FieldGT(FieldContextUpdatedBy, v))
}

// ContextUpdatedByGTE applies the GTE predicate on the "context_updated_by" field.
func ContextUpdatedByGTE(v string) predicate.Project {
	return predicate.Project(sql.FieldGTE(FieldContextUpdatedBy, v))
}

// ContextUpdatedByLT applies the LT predicate on the "context_updated_by" field.
func ContextUpdatedByLT(v string) predicate.Project {
	return predicate.Project(sql.FieldLT(FieldContextUpdatedBy, v))
}

// ContextUpdatedByLTE applies the LTE predicate on the "context_updated_by" field.
func ContextUpdatedByLTE(v string) predicate.Project {
	return predicate.Project(sql.FieldLTE(FieldContextUpdatedBy, v))
}

// ContextUpdatedByContains applies the Contains predicate on the "context_updated_by" field.
func ContextUpdatedByContains(v string) predicate.Project {
	return predicate.Project(sql.FieldContains(FieldContextUpdatedBy, v))
}

// ContextUpdatedByHasPrefix applies the HasPrefix predicate on the "context_updated_by" field.
func ContextUpdatedByHasPrefix(v string) predicate.Project {
	return predicate.Project(sql.FieldHasPrefix(FieldContextUpdatedBy, v))
}

// ContextUpdatedByHasSuffix applies the HasSuffix predicate on the "context_updated_by" field.
func ContextUpdatedByHasSuffix(v string) predicate.Project {
	return predicate.Project(sql.FieldHasSuffix(FieldContextUpdatedBy, v))
}

// ContextUpdatedByEqualFold applies the EqualFold predicate on the "context_updated_by" field.
func ContextUpdatedByEqualFold(v string) predicate.Project {
	return predicate.Project(sql.FieldEqualFold(FieldContextUpdatedBy, v))
}

// ContextUpdatedByContainsFold applies the ContainsFold predicate on the "context_updated_by" field.
func ContextUpdatedByContainsFold(v string) predicate.Project {
	return predicate.Project(sql.FieldContainsFold(FieldContextUpdatedBy, v))
}

// ContextUpdatedAtEQ applies the EQ predicate on the "context_updated_at" field.
func ContextUpdatedAtEQ(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldContextUpdatedAt, v))
}

// ContextUpdatedAtNEQ applies the NEQ predicate on the "context_updated_at" field.
func ContextUpdatedAtNEQ(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldNEQ(FieldContextUpdatedAt, v))
}

// ContextUpdatedAtIn applies the In predicate on the "context_updated_at" field.
func ContextUpdatedAtIn(vs ...time.Time) predicate.Project {
	return predicate.Project(sql.FieldIn(FieldContextUpdatedAt, vs...))
}

// ContextUpdatedAtNotIn applies the NotIn predicate on the "context_updated_at" field.
func ContextUpdatedAtNotIn(vs ...time.Time) predicate.Project {
	return predicate.Project(sql.FieldNotIn(FieldContextUpdatedAt, vs...))
}

// ContextUpdatedAtGT applies the GT predicate on the "context_updated_at" field.
func ContextUpdatedAtGT(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldGT(FieldContextUpdatedAt, v))
}

// ContextUpdatedAtGTE applies the GTE predicate on the "context_updated_at" field.
func ContextUpdatedAtGTE(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldGTE(FieldContextUpdatedAt, v))
}

// ContextUpdatedAtLT applies the LT predicate on the "context_updated_at" field.
func ContextUpdatedAtLT(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldLT(FieldContextUpdatedAt, v))
}

// ContextUpdatedAtLTE applies the LTE predicate on the "context_updated_at" field.
func ContextUpdatedAtLTE(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldLTE(FieldContextUpdatedAt, v))
}

// ContextUpdatedAtIsNil applies the IsNil predicate on the "context_updated_at" field.
func ContextUpdatedAtIsNil() predicate.Project {
	return predicate.Project(sql.FieldIsNull(FieldContextUpdatedAt))
}

// ContextUpdatedAtNotNil applies the NotNil predicate on the "context_updated_at" field.
func ContextUpdatedAtNotNil() predicate.Project {
	return predicate.Project(sql.FieldNotNull(FieldContextUpdatedAt))
}

// HasMembers applies the HasEdge predicate on the "members" edge.
func HasMembers() predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, MembersTable, MembersColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMembersWith applies the HasEdge predicate on the "members" edge with a given conditions (other predicates).
func HasMembersWith(preds ...predicate.ProjectMember) predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := newMembersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasInvites applies the HasEdge predicate on the "invites" edge.
func HasInvites() predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, InvitesTable, InvitesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasInvitesWith applies the HasEdge predicate on the "invites" edge with a given conditions (other predicates).
func HasInvitesWith(preds ...predicate.ProjectInvite) predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := newInvitesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSessions applies the HasEdge predicate on the "sessions" edge.
func HasSessions() predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SessionsTable, SessionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSessionsWith applies the HasEdge predicate on the "sessions" edge with a given conditions (other predicates).
func HasSessionsWith(preds ...predicate.AgentSession) predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := newSessionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAgents applies the HasEdge predicate on the "agents" edge.
func HasAgents() predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AgentsTable, AgentsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAgentsWith applies the HasEdge predicate on the "agents" edge with a given conditions (other predicates).
func HasAgentsWith(preds ...predicate.Agent) predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := newAgentsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasNotes applies the HasEdge predicate on the "notes" edge.
func HasNotes() predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, NotesTable, NotesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasNotesWith applies the HasEdge predicate on the "notes" edge with a given conditions (other predicates).
func HasNotesWith(preds ...predicate.ProjectNote) predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := newNotesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Project) predicate.Project {
	return predicate.Project(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Project) predicate.Project {
	return predicate.Project(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Project) predicate.Project {
	return predicate.Project(sql.NotPredicates(p))
}
