// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AgentSession is the predicate function for agentsession builders.
type AgentSession func(*sql.Selector)

// CliCredential is the predicate function for clicredential builders.
type CliCredential func(*sql.Selector)

// Event is the predicate function for event builders.
type Event func(*sql.Selector)

// Project is the predicate function for project builders.
type Project func(*sql.Selector)

// ProjectInvite is the predicate function for projectinvite builders.
type ProjectInvite func(*sql.Selector)

// ProjectMember is the predicate function for projectmember builders.
type ProjectMember func(*sql.Selector)
